### ISSUE TITLE
In teacher tips address user reported issue: helium balloon

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balloons-and-static-electricity#117]
User reported via PhEThelp on 1/21

Report a Problem: Balloons and Static Electricity

Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks. 

Test device: iMac (27-inch, Late 2013), 3.2 GHz Intel Core i5

Operating System: Mac OS X 10.11.12

Browsers: Chrome, Safari

Problem description: **Ideally, assuming the balloon is filled with helium, it should drift back upwards after being released, since it has not received any charge.**

Steps to reproduce: Move uncharged balloon(s) left or right. 

Severity: Moderate, students in my grade 8 class have asked about this.

Screenshots: 

Troubleshooting information (do not edit):
Name: Balloons and Static Electricity
URL: http://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html
Version: 1.0.0
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1861x1314
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by oliver-phet** [comment]
@ariel-phet Can you comment if this is something we are going to respond to?

**Comment by ariel-phet** [comment]
@oliver-phet - this is a very intentional choice. We don't want to conflate the idea of a buoyant force on the balloon with the electric forces on the balloon. It would be a very confusing user experience if the uncharged balloon floated up. Nobody claimed the balloons were helium filled, but the string is assumed to be "magic" and keeps the correct tension to keep the balloon in place.

We will not address, but we can make a note in the teaching tips.

**Comment by oliver-phet** [comment]
Thanks, I'll reply to the user.

**Comment by ariel-phet** [comment]
Cool, please leave the issue open, I will assign it as a teaching resources enhancement

**Comment by arouinfar** [comment]
This simplification has been documented in the teacher tips, which I'll finish up later today or sometime tomorrow. Since the tips document is being tracked in #119, I'll go ahead and close this issue.

**Comment by terracoda** [comment]
@ariel-phet @oliver-phet @arouinfar This is an important detail to add to the scene description in the accessible version of this simulation. I thought I should describe the balloons as helium balloons, but I refrained because they do not behave like helium balloons.

Nice to know the string is "magic". Can we consider reversing the situation, so that the balloons are hanging from the ceiling? It might be more "implicitly" obvious that they are not actually helium balloons, then, although the strong would still be "magic."

If anyone is interested, I did an art installation of this simulation last summer at OCAD University with both helium and non-helium balloons and found the following:
* non-helium balloons hanging from the ceiling (or hanging from a helium balloon) behave most like the simulation
* balloons with a pearl-like sheen seem to collect negative charge differently (have to check my notes, but I think pearlized balloons seemed to get a stronger charge).
* balloons with the special sealant squirted inside that helps make them last longer affects the balloon's capacity to pick-up (or hold) negative charge; balloons treated with the sealant didn't hold negative charge as well as non-treated balloons.
* helium balloons with a little air mixed in were less forcefully buoyant (obviously) and performed more like the simulation than balloons filled exclusively with helium which had a strong force from the helium.

Links to the installation and photos are here on my website at http://terracoda.ca/research/experimental-play.html

I'll add the idea of a "magic" string to the description of the accessible simulation.

**Comment by arouinfar** [comment]
Thanks for your insights @terracoda! I enjoyed looking through your installation photos. One thing I hadn't thought about until I read your comment is that we will probably need to create new teacher tips for sims when they are re-released with accessible features. 

Here's the text from the model simplifications of the teacher tips
> Uncharged balloons will stay wherever they are placed, and the string attached to them will maintain the appropriate tension to hold the balloon in place. The buoyant force acting on the balloons is intentionally not modeled in this simulation, so that students do not conflate the idea of the buoyant force on the balloons with the electric forces on the balloons.

I like @terracoda's suggestion to hang the balloons from the ceiling. I think it would definitely help cue that the balloons are not helium filled (or that the buoyant force is not present/shown). I'm going to reopen this issue and reassign to @ariel-phet to comment on whether or not this is something we should consider for the redeploy.

**Comment by terracoda** [comment]
Thanks for the descriptive note @arouinfar. And I am happy to contribute. Glad you like the hanging from the ceiling idea. In my installation, I suspended non-helium balloons with helium filled ones and it had a really nice effect. Hopefully, some day I'll get to do the installation again.

**Comment by ariel-phet** [comment]
@arouinfar lets close this issue (since things were addressed in the teacher tips for the current version). Please make a new issue and mark as an enhancement, something like "consider hanging balloons from ceiling" copy over relevant comments, and reasoning.

**Comment by arouinfar** [comment]
Will do @ariel-phet!
