### ISSUE TITLE
Shift plus WASD keys

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#125]
In Instance 11, it appears that when adding Shift to one of the WASD keys doesn't make the balloon take bigger steps. Did something change? I've tested with JAWS 17 on Windows 10 and on Mac with no screen reader.

**Comment by jessegreenberg** [comment]
In a previous issue, we found that the default drag speed was too slow on certain platforms to pick up charges.  Now that the default speed is increased, the difference between fast and slow dragging may seem negligible.  I will increase the 'fast' dragging speed a bit so that the difference is more apparent.

**Comment by jessegreenberg** [comment]
Speed increased when shift pressed, closing.

**Comment by terracoda** [comment]
Awesome @jessegreenberg, thank you!
