### ISSUE TITLE
Dash in control panel accessible labels

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#172]
In the design document, there is a request to add dashes to some of the button labels.  @terracoda would you please explain why?  Some screen readers will read this dash explicitly.  For a button like
```html
<button>Two-balloon experiment button</button>
```
NVDA reads *"Two dash balloon experiment, button"*.  Is this intentional?

**Comment by terracoda** [comment]
@jessegreenberg, the dash is grammatically correct because the two words "Two" and "balloon" together form one adjective phrase modifying the word "experiment". Now, it is true that dashes do get dropped often.

In interviews, there was one participant who did not understand the word "two". They thought it was "to" until they listened letter by letter, and then they got it. Honestly, I'm not sure which is best for screen reader users, I was just going with good grammar :-) Let's try the dash and see how users respond.

**Comment by jessegreenberg** [comment]
> They thought it was "to" until they listened letter by letter, and then they got it.

I can see how that would be confusing!  Sounds good, closing.
