### ISSUE TITLE
Add visual cue for 'Grab Balloon' button

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#206]
In some informal testing and examples, we have seen that sighted users do not understand that the balloon has to be 'picked up' in order to drag with the keyboard.   In 11/15/16 accessibility meeting, we discussed possibilities of using a visual cue to indicate that the balloon needs to be picked up.  We mentioned examples of such cases like
 - Moving icons on desktop
 - Shaking icons on iPad when tap and hold

Right now, the focus highlight changes color once the balloon has been picked up, but this doesn't provide an indication that the balloon should be picked up for dragging the first time.

@terracoda do you have any thoughts on creating something like this?

**Comment by terracoda** [comment]
@jessegreenberg, really? How many sighted users are having trouble grabbing the balloon?

I wonder if this might be part of a life experience mismatch. For example, my partner, who grew up in India asked about what to do with the balloon when he first looked at the sim. He didn't wear sweaters very much as a kid. They way he and his friends learned about static electricity was by playing with a comb and their hair.

Does the balloon have a string? I noticed recently that the balloon in the a11y dev version has lost the string. I'm wondering if the string might have an influence on the decision to grab the balloon?

**Comment by terracoda** [comment]
@jessegreenberg, it might make it more clear to a user that the balloon needs to be grabbed if temporary arrows show up on hover, like they do in the Concentration sim or the Bending Light sim. I think the behaviour in Concentration might be better suited to BASE. @emily-phet and others were just discussing this for the visual keyboard cueings, as well.

**Comment by jobara** [comment]
@terracoda if I understood things correctly at the meeting yesterday, the issue isn't so much that they don't understand that they need to interact with the balloon, but that they didn't realize there was a distinct action required to "grab" the balloon before it could be moved. Hope that helps.

**Comment by terracoda** [comment]
@jessegreenberg and @jobara, sorry, I was confused about the initial comment. My understanding was that it was a visual mouse/touch user that was having trouble.

However, if we are discussing a visual keyboard user or switch device user then this is not a new consideration. There is currently no visual indicator to tell the user that the Balloon is a button (NOW a button, it wasn't before) and that it must be grabbed.

The full interaction actually has three steps:
- __Enter key or Space bar to grab the balloon__. In the un-grabbed state the balloon is a button.
- __Space bar to release it__. In grabbed state it is no longer a button, but  a custom Application widget. (Note that I had a comment from one participant who was blind that the Space bar was intuitive. They mentioned that they often use Space bar to pick things up or jump.)
- __WASD keys to drag and rub it (i.e. move it). Of course, without a screen reader, the Arrow keys are available for balloon dragging/rubbing.

There may be at least two ways to handle this:
In all cases, we must first make it very clear how to get to the information that contains "Hot Keys and Keyboard Help" dialog sheet. We were discussing this keyboard help button in another issue with @arouinfar, @ariel-phet and @emily-phet  (I will add the link to that issue).

__Possible focus solutions:__
1. Create a temporary visual, i.e., an initial visual on the balloon. This visual could be something that looks more button-like. This button-like visual could appear upon keyboard focus, and disappear once  the user presses Enter or Space bar. 
2. Create a tool tip that indicates that there is indeed a button there.
3. Create some other visual keyboard focus indicator (I am not 100% sure visual arrows will work, but the might.)

Then once the the button is pressed, the balloon is grabbed, and the visuals needs to make that clear, and would also indicate that the balloon can be dragged (or rubbed) with the WASD keys (or Arrow keys).

__Possible focus, then grabbed solutions:__
1. A arrow-driven visual could be blank Arrows on focus, and then Arrows with the letters added, once grabbed. The change between the focused and grabbed states could also include a color change and/or a dotted or dashed line changing to solid (or both).
2. A tool tip-driven solution would need to start with the information about the presence of a button and then change once grabbed to indicate that the WASD keys or Arrow keys are available for dragging.

__Still missing the Space bar for the release mechanism__
We can easily add text to a tool tip to indicate the release mechanism, but indicating the release mechanism visually with Arrows would be trickier.

Sorry, for the long post. I hope that clarifies the interaction pattern and summarizes the thinking on it, thus far.

**Comment by terracoda** [comment]
@jessegreenberg, @jobara, @emily-phet 
I'll just add that the current interactions appear to be very intuitive for people who use screen readers.

For the record, the on-demand help text for the Grab button and the automatic help text for the grabbed Balloon are outlined in the first tab (PDOM tab) in [Base Labels & Descriptions](https://docs.google.com/spreadsheets/d/1BiXFN2dRWfsjqV2WvKAXnZFhsk0jCxbnT0gkZr_T5T0/edit#gid=0)

**Comment by jessegreenberg** [comment]
> I'll just add that the current interactions appear to be very intuitive for people who use screen readers.

Yes I agree @terracoda!  I think the only issue is the one pointed out by @jobara (https://github.com/phetsims/balloons-and-static-electricity/issues/206#issuecomment-260947064).

Thanks for defining the interactions in https://github.com/phetsims/balloons-and-static-electricity/issues/206#issuecomment-260970836, those possibilities sound good.

> In all cases, we must first make it very clear how to get to the information that contains "Hot Keys and Keyboard Help" dialog sheet.

I agree that this would be very helpful.

For a solution using an arrow driven visual, I wonder if this could have an adverse affect, indicating that the balloon can be dragged with the keyboard immediately before picking it up with the button.

**Comment by terracoda** [comment]
@jessegreenberg, I wonder the same as you...
>  using an arrow driven visual, I wonder if this could have an adverse affect, indicating that the balloon can be dragged with the keyboard immediately before picking it up with the button.

I think it would best if arrows and the WASD letters only show up once the balloon is grabbed.
 
I wonder if we can make a cue (i.e. focus) that is more button-like without making the balloon look ugly, that might be better. I feel that the arrows and letters should show up after the balloon is grabbed. The visual problem is that the balloons do not come with buttons.

**Comment by terracoda** [comment]
@jessegreenberg, @jobara, I made another quick sketch of a possibility. It's a combination of tool tip (as suggested by @jhung)  and arrows. The original sketches that I shared with Mel were based on the old interaction. 
![img_2157](https://cloud.githubusercontent.com/assets/1902116/20372331/f2351e5e-ac44-11e6-845b-12119e0bb5c6.JPG)

The first column are three Focus sketches, the second column is Grabbed states, then Dragging, and then Released.

**Comment by terracoda** [comment]
The current text that screen readers announce/verbalize is:
- On focus: Grab Yellow balloon, button.
- On Grab: (Yellow Balloon). In centre of Play Area. Has no more negative charges than positive charges.
- While dragging, interaction alerts and dynamic descriptions are announced.
- On Release: Grab Yellow balloon, button. (Yellow balloon). (And a release update, movement, sticking state and position).

**Comment by arouinfar** [comment]
@terracoda I can mock up the options in your sketch https://github.com/phetsims/balloons-and-static-electricity/issues/206#issuecomment-261124748 in Illustrator, if it would be helfpul.

**Comment by terracoda** [comment]
@arouinfar, actually, a young designer volunteering with the IDRC - her name is Mel - took a stab at my first sketches. She hasn't had a chance yet to digitize this idea yet. I'd like to give her the opportunity to do that. Mel's illustrator sketches are in the folder I shared with you.

**Comment by arouinfar** [comment]
Excellent @terracoda! I'm happy to let you and Mel handle this. 

I remember we had discussed the possibility of creating Illustrator mockups some time ago, and I wanted to follow up and see if there was anything you'd need from me.

**Comment by terracoda** [comment]
@arouinfar, yes we discussed this before. It would be great to get the PhET perspective once Mel gives it a go.

**Comment by arouinfar** [comment]
Absolutely, I'd be happy to chat with you and Mel further as things progress.

**Comment by terracoda** [comment]
Awesome. Thanks @arouinfar.

**Comment by melbanyard** [comment]
@arouinfar , @terracoda On this now, I may have a couple questions to confirm during this Tuesday's meeting. Would it be best to upload the sketches here?

**Comment by melbanyard** [comment]
[BalloonsStaticElectricity_KeyboardAccessVisuals_V.02.pdf](https://github.com/phetsims/balloons-and-static-electricity/files/602669/BalloonsStaticElectricity_KeyboardAccessVisuals_V.02.pdf)

**Comment by terracoda** [comment]
@melbanyard, thanks for mocking the 3 examples up so quickly. It will be great to get @arouinfar's feedback. I have a few discussion points about the current mock-up, which you may already be thinking about:

1. The focus and grabbed states can't share the same look for the outline. The outlines for the focused and grabbed states need to be different because they are distinctly different states. The focus state is an inactive/unpressed state and the grabbed state is an active/pressed state.
2. The grabbed and dragging states can share the same look for the outline for similar reasoning. The grabbed and dragging states are technically the same. It is just that the user no longer needs the visual keyboard cue after one or two steps.
3. I think I prefer a solid line to a change in background-color because I'm not sure how much the shape of the balloon influences the picking up of charges. The background color might may a user thing that the full square is an active rubbing space.
4. I think the grabbed/dragging state always needs to have a visual indicator (in my sample drawing, I think it was a mistake to leave off the grabbed outline in example 3, sorry). The outline tells the user where their keyboard focus is. It's analogous technically to a pressed or active state, as opposed to just the focused (unpressed, inactive) state.
5. The outline might need to be tight on the edge of the balloon to facilitate being against the wall or near the wall and at other extreme locations.

I also want to discuss the use of language in the tool tips. I'm not sure how much the language needs to be the same or similar for both a screen reader user and a visual keyboard user. This is a very interesting design question. They each have different needs.

**Comment by melbanyard** [comment]
@terracoda Thanks! This was definitely mocked up rather quickly and I'd like to spend more time exploring different styles, colours, line weights and your recommendations mentioned above etc.

I'll start by working on differentiation the focus, grabbed and dragged states. I did have one question while I was doing this however - Does the light white I used meet accessibility standards? I considered experimenting with different colours, brightnesses, (or outlining the balloon, rather than placing it in a box) but wasn't sure how this might affect the SIM as whole.

**Comment by terracoda** [comment]
@melbanyard, your mock-up is great. It is much better thing to discuss than pencil drawings!

In case I wasn't clear, the grabbed and dragged are technically the same state (active/pressed), and released and focused are also technically the same state (inactive/unpressed).

I was also concerned about the shade of the box color. To check the contrast between blue and the white-ish box color, you can try one of these tools linke to below. It is easiest to test contrast with the actual color code. Using more than color to make it clear between the focused and grabbed states is ideal...as an example, a change from a colored dashed line to a differently colored solid line makes the change clear to both people who distinguish the color difference easily and those who do not.

- [WebAIM's contrast checker](http://webaim.org/resources/contrastchecker/)
- [Lea Verou's contrast checker](http://leaverou.github.io/contrast-ratio/)

I also missed something in the mock-up. The release action, is "Space bar", so we likely need another tool tip for that, too.

Keep in mind, I think the tool tips and arrows are visuals that likely will go away once it is clear the user has learned these interactions.

**Comment by terracoda** [comment]
This issue is on hold as we determine requirements for the Keyboard Hotkeys and Help button. Closing for now.

**Comment by jessegreenberg** [comment]
Reopening and adding the on-hold label.

**Comment by jessegreenberg** [comment]
In a meeting 1/24/17 @ariel-phet mentioned an idea to embed keyboard interaction icons into the focus highlight.  The icon in the focus highlight could then be mapped to an icon in the keyboard help dialog.

PhET could create a system of icons for various interactions and these icons could be applied to various interactive elements.  For instance, a radio button group might not look like radio buttons in a sim, but an icon in the focus highlight might cue the user to the appropriate interaction.

**Comment by melbanyard** [comment]
Hello! I'll be working on this this week as I didnt receive any other updates. To clarify, are there any outstanding changes to be made to the keyboard mock ups aside from those specified by @terracoda above? I've missed some discussion of course.

**Comment by terracoda** [comment]
@melbanyard, I have no further direction to give you except that there seems to be 2 seperate issues:
1. communicating a standard keyboard interaction to a visual user when the interaction in the sim does look like a standard control like a button. The "Grab Yellow Balloon" button is an example.
2. Communicating custom interactions like the rub/drag interaction to visual users. 

I think number 1 is the priority, and you have seen examples of how some PhET sims do this already with arrows and highlights that fade away after successful interaction.

**Comment by melbanyard** [comment]
[https://drive.google.com/file/d/0BxijvNkPCfR-R0xNWV9KcDZqc1k/view?usp=sharing](url)

a link to the latest!

**Comment by terracoda** [comment]
@melbanyard, that link does not work for me. Can you double check it?

**Comment by emily-phet** [comment]
@melbanyard After reviewing your [latest designs](https://drive.google.com/file/d/0BxijvNkPCfR-OFZZbE80a2VFdGM/view), here are a few thoughts:
- It would be nice if the information provided to grab and to release were the same. For example: [Spacebar] or [Enter] to Grab or Release. 
- Once grabbed, I like the letter keys with the added arrow-like detail (the bottom option for the Grabbed state). I think using the keyboard key look whenever possible helps with the mapping we want users to do. 
- I think we should try having the cue to use spacebar or enter key appear whenever the balloon has focus *until* the user successfully grabs the balloon. Then no more visual cue for this. And the same for the grabbed cue - it appears each time the balloon is grabbed *until* the user successfully moves the balloon. 

@jessegreenberg Can you update on whether the arrow keys will move the balloon in NVDA/JAWS/VO? I have some memory that it still won't in JAWS, so WASD keys are required for JAWS users...can you confirm this is still the case?

Also, I'm planning to share your mockups with some of the PhET team at a design meeting on Thursday (time TBD). You're welcome to join, of course. I'm just looking for some general feedback, and a quick double check that no one has any further ideas for how to address this problem without onscreen text. (I worry about this approach down the road - translation, etc. - so I'm still hopeful there might be some way around this...)

**Comment by melbanyard** [comment]
Hey Emily,

Thanks for the feedback! I'll work on making these changes after your
Thursday meeting. Is it a virtual meeting? If so, I'd love to sit in and
listen to what other's thoughts are.

Mel

**Comment by jessegreenberg** [comment]
I just tested with the latest version of JAWS (18.0.2738) and https://github.com/phetsims/a11y-research/issues/9 bug is still happening, so arrow keys are not usable with JAWS.

**Comment by arouinfar** [comment]
@melbanyard thanks for working on these mockups. @emily-phet has made some excellent points. I think it would be preferable to combine the Grab and Release information into one cue that appears each time balloon is focused (until the balloon is first grabbed). However, I've noticed that the balloon cannot be released with Enter -- only Space. We would either need to add release support to Enter, or modify the text to read "Grab or Release with [Space]".  I personally like this layout quite a bit:
<img width="181" alt="screen shot 2017-04-19 at 12 59 21 pm" src="https://cloud.githubusercontent.com/assets/8419308/25197102/11ab7556-2500-11e7-9bb4-687a18d8b257.png">

In the Grabbed state, I also quite like the cueing arrows that look like keyboard keys. Once the balloon is moved, these cues can disappear permanently.
<img width="150" alt="screen shot 2017-04-19 at 12 59 28 pm" src="https://cloud.githubusercontent.com/assets/8419308/25197101/11aa5374-2500-11e7-90da-882f10df5bd7.png">

I'm not sure that we'll need cues for any other of the other states. I think the "Grab or Release with [Space]" text in the Focused state and the WASD cue in the Grabbed state should be sufficient.

**Comment by terracoda** [comment]
Just for reference, I am posting a summary of the challenge here because I accidentally started a new issue 3 weeks ago. I am going to close that issue ( #256 ) so the conversation can continue here.

**General Issue** 
Interaction Hints for visual keyboard users are needed for custom interactions or for when the interaction is not implicitly obvious to a user who can see, but who may not use a mouse. A user may use AT such as the keyboard or switch to navigate and interact with the sim. A user who uses a keyboard with a screen reader is able to access structural information and descriptions that guide the interaction. Visual keyboard users, however, may need to first read the Keyboard Shortcuts dialog to gain an understanding of how the sim works with a keyboard., but may have trouble when they just try to use the sim without reading that information.

**Challenge 1: Standard Button Interaction, but Invisible**
The interaction to grab the balloon is executed by pressing the grab balloon button. However, this interaction is not obvious to visual keyboard users because the balloon does not visually resemble a button.

**Challenge 2: Arrow keys & Custom Hot Keys to Drag Balloon**
Once the balloon is grabbed, a user can use the Arrow keys to drag the balloon up, left, down or right. The Arrow keys should be fairly intuitive, but a reassuring hint my be needed. The user can also use a set of custom Hot Keys: W key (to go Up), A key (to go Left), S key (to go Down), or the D key (to go Right). These keys are common to gamers, and with some screen reader software the Arrow keys are unavailable for this interaction.

**Comment by terracoda** [comment]
@melbanyard, I agree with @emily-phet and @arouinfar, there are technically only two states:
- **focus** - the user has keyboard focus on the balloon, and they need to know how to grab and release it.
- **grabbed** - the user has grabbed the balloon needs only an initial hint on how to drag (i.e., move it).
  - the visual grabbed state is simplified (i.e., the hint disappears) after successful movement.

I also agree with @arouinfar, that we only need to cue the [Space] key. I've been thinking about this for a while, and wondering if the Grab and Release should be exactly the same (both [Enter] and [Space]), but regardless, we only need to cue one of the keys. The Keyboard Shortcut doc can handle all the details.

**Comment by terracoda** [comment]
**Oops,** not finished with my feedback in previous post...
- I also like the keyboard idea, but due to limited size space and more complicated interactions for other sims, I'm not sure how far we can get with the keyboard visual.
- Since we are currently, using a bright pink for focus in other designs to show keyboard focus could you update the mock-up to use the pink solid outline, and use the dotted-black outline for the grabbed state only. It's important to not use color only to indicate a change.
- On release, the line would become a solid pink again. 
- Personally, after a few successful interactions (grab, drag, and release), I don't think the user will need a visual cues, but we can discuss that at a later date once we have the initial cue ironed out.
- Finally, what do people think of keeping solid arrows, but having them a little separated, so they, too, look like keys.

**Caution with Visual Text**
Though I really like "Grab me", this is not the label I used text that is used on the button. The actual label text is "Grab Yellow Balloon", or "Grab Green Balloon", depending on the balloon. I'm not sure how forgiving voice activation software, like Dragon, is. "Grab" alone may work, but "Grab me" likely won't. This needs further investigation.

**Possible very Rough Adjustments**
Sorry, these are big!
![balloonkeys-focus-key-first](https://cloud.githubusercontent.com/assets/1902116/25603563/7595f658-2f1a-11e7-9987-80e8eb574417.png)
![balloonkeys-focus-key-second](https://cloud.githubusercontent.com/assets/1902116/25603565/782a213c-2f1a-11e7-8778-2a221ce7805a.png)
<img width="378" alt="balloonkeys-mel-v2-adjusted" src="https://cloud.githubusercontent.com/assets/1902116/25603572/7d78c918-2f1a-11e7-95b8-d62dbd988bd6.png">

**Comment by terracoda** [comment]
Text in the cues could be a variety of things, I was trying to minimize. And, like Amy, I think I prefer the border around the word, "Space".
- "[Space] to grab or release."
- "[Space] to grab or let go." 
- "Grab or release with [Space]."
- "Grab or let go with [Space]."
- "Grab or let go {line break} [Space]."
- "Grab / Let go with [Space]."
- "Grab / Release {line break} [Space]."

Do people have a preference for over using "/" or "or"?

**Comment by terracoda** [comment]
@melbanyard, posting your nice Version 2 visuals here for reference.
<img width="962" alt="screen shot 2017-05-02 at 09 54 40" src="https://cloud.githubusercontent.com/assets/1902116/25603873/7159bc16-2f1d-11e7-9def-83b970dabbf8.png">

**Comment by terracoda** [comment]
Adding @emily-phet 's comments here:
On May 2, 2017, at 17:45, Emily B Moore <emily.moore@colorado.edu> wrote:

Hi Mel,

Thanks! I really like the simple “[Space] to Release” graphic…it’s making me re-think if we really need to provide both the spacebar and enter options…I’ll bring this up at the noon MT/2pm ET meeting today.

I agree with Amy, I think the full keyboard graphic is aesthetically nice, but I’m just not sure it will be understandable to a broad enough audience.

Can you mock up versions of the three options Amy lists with these looks:
Focused (but not grabbed) state -  with “Space to Grab”, and the “Space” looks like a button.  
Grabbed state - “Space to Release”, and “Space” looks like a button
First move/dragging - WASD with light carrot symbols (as you have it already) 

Best, 

~ Emily

**Comment by melbanyard** [comment]
Hi Everyone,

There's a lot of feedback here! I'm working on this now and will share on our Tuesday meeting. I'm not quiet sure if I'm moving in the right direction, so some face to face discussion would be helpful. :)

**Comment by melbanyard** [comment]
I've also scrapped the keyboard icon idea and am moving forward without it.

**Comment by melbanyard** [comment]
[Phetsims_pass5.pdf](https://github.com/phetsims/balloons-and-static-electricity/files/1020150/Phetsims_pass5.pdf)

**Comment by melbanyard** [comment]
[Phetsims_pass5.pdf](https://github.com/phetsims/balloons-and-static-electricity/files/1020154/Phetsims_pass5.pdf)

Hello! I've attached my most recent version(s) of the keyboard visuals here. I updated the styling on #2, to better compliment the visuals that @terracoda designed for the tip sheet we looked in last week's meeting. I'm leaning towards that, I think they're easier to make out. How do we feel about these? @arouinfar @emily-phet

**Comment by terracoda** [comment]
I (@terracoda) helped with the visual design of the Keyboard Shortcuts dialog. @arouinfar did the more polished layout that I shared at our last meeting (#263). I think it is very useful to keep a similar look and feel whenever possible, so it's very good that you are aiming to do just that, @melbanyard.

**Comment by arouinfar** [comment]
@melbanyard I prefer the styling on #2. It's a bit more minimal and I think it's a good fit with the style used in Keyboard Shortcuts menu. We could add drop-shadows to the key icons to make them look a bit more like the icons in the Keyboard Shortcuts menu, but I think that will look too heavy in this context.

**Comment by emily-phet** [comment]
@melbanyard We discussed the latest designs today. We all prefer the lower panel option (it looks great!). Could you make a version of the lower panel with a thin black line around the white rectangle that contains the "Space to grab or release" text. 
Once that's done, we can go ahead and move forward with implementing this design!

**Comment by melbanyard** [comment]
Can do!

**Comment by melbanyard** [comment]
[BASE_KeyboardVisualCues.pdf](https://github.com/phetsims/balloons-and-static-electricity/files/1033232/BASE_KeyboardVisualCues.pdf)

**Comment by terracoda** [comment]
Thanks @melbanyard, and looks good!

**Comment by emily-phet** [comment]
@melbanyard - perfect! I think we're good to go here. Jesse is focused on implementing all the latest designs for BASE over the next few weeks, so we'll get to see this in action soon! Thanks so much for your efforts on this.

**Comment by arouinfar** [comment]
Looks great @melbanyard!

**Comment by terracoda** [comment]
@emily-phet, to be in line with the new visual, I will update the wording for instances of "Space key to let go" to "Space to release" in the non-visual experience.

If this needs further discussion, we may need to open a new issue specifically related to changes in the PDOM.

Again, great work @melbanyard!

**Comment by emily-phet** [comment]
@terracoda This sounds fine to me.

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet @arouinfar the mockup in https://github.com/phetsims/balloons-and-static-electricity/issues/206#issuecomment-304418947 has keys without the shadow used in the keyboard help dialog.  Is they intentionally different or should they be the same as the help dialog keys?

**Comment by terracoda** [comment]
@jessegreenberg good catch. 
Mel's visual design was definitely aiming to make the letter keys look like keys on a keyboard (and more inline with the keyboard help dialog), but it is true the final mock-up that was agreed on does not have the drop shadow. I'm not sure if this was intentional due to the proximity to the Arrows.

@jessegreenberg, is the drop shadow implemented as a separate piece? Would it be easy to add/remove?

@emily-phet, I think it makes sense to keep the images consistent unless the drop shadow does not look good next to the Arrows.

**Comment by terracoda** [comment]
@emily-phet, for a quick comparison, @jessegreenberg has implemented the drop shadow on the Space key in the latest version, and I think it looks good.

**Comment by emily-phet** [comment]
@terracoda I agree it makes sense to keep the visual design consistent between visual cues and the keyboard help dialog. Let's do that unless it causes a problem.

**Comment by terracoda** [comment]
Thanks @emily-phet! 
@jessegreenberg, please implement the WASD keys cue with a drop shadow, and we go from there.

**Comment by jessegreenberg** [comment]
Sounds good!

**Comment by jessegreenberg** [comment]
@melbanyard  @terracoda @emily-phet @arouinfar this has been implemented in http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.1/balloons-and-static-electricity_en.html?accessibility

Can you please review and let me know if you have any thoughts or concerns?

**Comment by terracoda** [comment]
@jessegreenberg, I think the implementation look great. Regarding function, the balloon is not always releasing correctly. I sometimes still have dotted grabbed line after release, or the balloon does not actually release and move, just stays grabbed.

**Comment by arouinfar** [comment]
@jessegreenberg I really like it! I tested it out in latest Mac/Chrome, and I wasn't able to reproduce the issues described by @terracoda.

**Comment by terracoda** [comment]
@jessegreenberg, I was using FF 54.0.1 64 bit on Mac OS Sierra 10.12.3. The balloon only releases if I keep holding Space down, or if I tab away. The visuals look great, though.

**Comment by jessegreenberg** [comment]
Alright, thanks everyone, I think this is all set!  I will track the bug mentioned by @terracoda in a new issue.

Closing.
