### ISSUE TITLE
Consider "scene selection" buttons for one vs two balloons

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balloons-and-static-electricity#213]
@jessegreenberg another little thing I was noticing for BASE

Again this is one of the first sims we converted and we had not really pegged down our HTML5 look and feel. It seems that the convention we have settled on for things like one vs two balloons would be more appropriate for "scene selection" buttons much like we have in Faraday's Law for the one vs two coils.

Not a big deal, but something to consider.

**Comment by jessegreenberg** [comment]
@ariel-phet this was a change that we made for accessibility.  Here is how it looks in the deployed version:

![capture](https://cloud.githubusercontent.com/assets/6396244/21022652/a013ddac-bd3a-11e6-9a60-39d994a3c8aa.PNG)

Scene selection buttons are sun radio buttons, and it didn't make sense for an HTML radio button to make this kind of change to the play area (see #112).  So we changed both visual design and the representation in the Parallel DOM.

But if the prefered look is for something like Faraday's law we can change it to look like that and keep it acting like an ABSwitch in the Parallel DOM.

**Comment by jessegreenberg** [comment]
I will revert the visual, PDOM representation does not need to change what is in the scene.

**Comment by jessegreenberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/6396244/21031558/53bb1b38-bd61-11e6-9b99-ff3f3b210004.PNG)

@ariel-phet done in the above commit.  I am going to close since it is just reverting to look of published version.

mentioning @terracoda since this is something we discussed in #112 but this has no impact on representation in the PDOM.

**Comment by terracoda** [comment]
@jessegreenberg and @ariel-phet, I have a concern about keyboard focus and visual representation. Is it confusing if the control in the PDOM is on one focusable item, but in the visual it is 2 separate parts. Will the keyboard focus highlight go around both visual options? And with the click target to switch be the both visual spaces combined?

**Comment by ariel-phet** [comment]
@terracoda that concern is certainly valid, but the look of multiple selection buttons is in many of our sims, so we should figure the general a11y approach for this visual arrangement.

**Comment by jessegreenberg** [comment]
That is a good point @terracoda.  The focus highlight surrounds both buttons, spacebar toggles the value.  But each button has an individual mouse area.

In #112 I can't find why a radio button group doesn't make sense.  Do you remember why?  If it is a radio button, focus would be on the selected option and the arrow keys would toggle the value.  This would work with the mouse areas.

**Comment by terracoda** [comment]
@jessegreenberg, radio button strucure makes for more labels and controls, thus more verbosity. I had trouble making them sound action-oriented and still make sense. I think there were also some issues around how the different screen reader/browsers combos handled them. Radio button groups in particular had issues.

It's possible we know more now and could make it work better. The switch offers a single label and control, thus much ore succinct in a spoken mode.

It would be nice to discuss.

**Comment by terracoda** [comment]
@ariel-phet, @jessegreenberg should we set up a meeting for this.
Would you like some text-based examples of the different things I tried. 

I personally liked the label for a toggle (i.e. , switch) best becasue I felt it help tell a story in an outline of the sim. Tabbing through the focusable controls, a user hears:

- Grab Yellow Balloon, button
- Remove Wall, button
- Two-balloon Experiment, switch off (or off switch, or button not pressed)
- Reset Balloon, button
- Rest All, button

Note radio buttons for charge information were removed for our current study as we did not have descriptions for the different charge scenarios.

That seemed a lot better than something like this:
- Grab Yellow Balloon, button
- Remove Wall, button
- Play with two balloons, or just one, Radio Button Group
  - Add green balloon, radio button not checked, one of two
  - Remove green balloon, radio button, checked, two of two
- Reset Balloon, button
- Rest All, button

The second example is not only much longer, it just doesn't tell a cohesive story if read in isolation, which can happen. Also note that there were issues with counting the items in the group. For example, if we used a heading and help text, some screen readers counted that as an item in the group, so the user would get 3 of 4 and 4 of 4 with only 2 items to choose from... very confusing.

Let me know if I need to prepare something for a meeting. It's possible this might not be confusing to students in real life situations,  but the visual currently doesn't cue a checkbox (i.e. toggle button/switch) keyboard action (spacebar), which is slightly different from a button (spacebar and enter). A visual keyboard user might not immediately recognize what the interaction is with the two visual buttons.

**Comment by jessegreenberg** [comment]
@terracoda lets have an informal meeting about this just so I understand the issues.  If the visual style is required I think we should try to come up with something

**Comment by jessegreenberg** [comment]
@terracoda lets have an informal meeting about this so that I understand the issues with radio button group.  Radio button groups are something that we will want to use ini the future, so it will be important to figure out why they weren't working before, and why screen readers were counting the number of inputs incorrectly.  Do you have time for a chat this afternoon?

**Comment by terracoda** [comment]
@jessegreenberg How about now. I was just about to stop working :-)

**Comment by terracoda** [comment]
@jessegreenberg I'm on skype if you free now.

**Comment by terracoda** [comment]
@jessegreenberg, actually it's best if we could make time on Monday would that work for you?

**Comment by jessegreenberg** [comment]
Sounds great @terracoda, lets meet Monday.

> if we used a heading and help text, some screen readers counted that as an item in the group,

Ah, thats right, thanks.  Some screen readers counted everything under the "fieldset" as an item in the group so the following would be described as having 7 items instead of 3.
```html
<fieldset>
  <legend>Choose a shipping method:</legend>
  <input id="overnight" type="radio" name="shipping" value="overnight">
  <label for="overnight">Overnight</label><br>
  <input id="twoday" type="radio" name="shipping" value="twoday">
  <label for="twoday">Two day</label><br>
  <input id="ground" type="radio" name="shipping" value="ground">
  <label for="ground">Ground</label>
</fieldset>
```

We can try to avoid legends and labels.  We could also try a solution that doesn't use input type=radio. Something like this maybe:
http://oaa-accessibility.org/example/29/

**Comment by terracoda** [comment]
@jessegreenberg had a chat with Arial in this document [Toggle Switch vs. Radios](https://docs.google.com/document/d/1jaBhLoU83BsuOLhtJetwyt_A2FCc0ZiMNfnj5GbC7as/edit#)

And we decided on solution 3:
> Leave the visual as the current Scene Selection Boxes, but change the interaction so that the two buttons behave as one toggle switch button (i.e., increase the click target to match the area inside the focus highlight).

@ariel-phet suggested that you might need to 

> Create a switch component that has two visual options (Scene Selection boxes or Toggle Switch).

**Comment by jessegreenberg** [comment]
Sounds good @terracoda thanks.  I will start working on a new component.

**Comment by jessegreenberg** [comment]
Mostly done in the above commits.  I need to re-instrument for accessibility and then (probably) move the file to sun.

**Comment by jbphet** [comment]
This component is requiring extra work for phet-io instrumentation, since it doesn't use the standard radio buttons.  See https://github.com/phetsims/phet-io/issues/997.

**Comment by jessegreenberg** [comment]
@phet-steele and @jbphet have expressed some concern that being able to click on the selected button changes the state of the button, and that it seems odd to have an interactive element that looks like two buttons but behaves like one button.

@phet-steele also brought up the issue that if one button is made invisible through a PhET-iO wrapper, pressing the selected button will still toggle the value of the two radio buttons because clicking the selected visible radio button which is currently selected will still toggle the value.

In a keyboard navigation discussion on 1/31/17, it sounded like it is OK to have a difference in the number of interactive elements between mouse and keyboard.  For instance, a number tweaker like:

![capture](https://cloud.githubusercontent.com/assets/6396244/22519499/b50159ca-e86d-11e6-8dcb-abdc7846d98e.PNG)

Will be one focusable element where the values are changed with the arrow/number keys while the interaction mouse involves two clickable buttons.

@ariel-phet @terracoda could the same apply to this case?  With a mouse the button could behave like our normal radio button groups, but for accessibility it could still behave like a toggle switch.

**Comment by jessegreenberg** [comment]
I am also wondering if it will be problematic that the mouse/keyboard interaction for this button:
![capture3](https://cloud.githubusercontent.com/assets/6396244/22519878/5319409a-e86f-11e6-8a33-80fc82b0a3b3.PNG)

will be different than these buttons:
![capture2](https://cloud.githubusercontent.com/assets/6396244/22519893/633f2778-e86f-11e6-90ab-3a8d076c6eba.PNG)

when they are visually similar.

**Comment by terracoda** [comment]
I'd like to call @emily-phet in on this issue. @jessegreenberg, these are all interesting questions.

It is important to keep in mind that in both cases, the Space key is part of the standard interaction pattern. The Space key toggles a switch, and it can also check an unchecked radio button. Thus, it is not an unfamiliar interaction. Of course, in the case of scene selections here, one item is always selected, so hitting the Space key is not relevant for the group of 3 scene options.

It is the navigating between multiple radio buttons with arrow keys (something not possible with the a two-way switch) which makes the interaction seem different. Navigating to an unchecked radio will moves focus and checks it at the same time. My guess on why this is the standard keyboard interaction pattern for radios is that it saves time for keyboard users. It's like a single click with a mouse. If what you want is checked, you can tab away to the next thing. If you not happy with the current selection, you move and select simultaneously with the arrow keys.

Also, please keep in mind, that the only user data I have about this interaction is with screen reader users. There is no doubt in my mind that for screen reader users in the BASE sim, the switch provides a much better listening experience for users. Radio buttons did not sound good for this interaction.

I do not know how visual keyboard users (nor mouse users) will react to a visual focus highlight that surrounds two things that look like buttons, one greyed out and one not greyed out. These buttons hint at either being a checkbox or radio button because one is disabled, but they actually do not visually look like typical checkboxes or radio buttons in their checked or unchecked states.

The the switch role is technically a checkbox where only one option can be selected. Groups of radio buttons have the same restriction, only one can be selected. The switch offers efficiency when there are only two options.

Like @ariel-phet already mentioned, it is possible that visual mouse users won't even notice the larger click area that toggles the scene.

For groups of three or more, I do think that radios make sense in the PDOM to represent scene selection options when there are three or more.

I think we will have to interview visual keyboard users to see how they handle these scene selection buttons.

**Comment by terracoda** [comment]
@jessegreenberg, as for the spinbutton example, it actually looks like what it is (a spinbutton). I would think that the interaction would be familiar to all users, mouse users, visual keyboard users, and screen reader users.

I don't think there is a potential visual/non-visual mismatch in this case.

**Comment by ariel-phet** [comment]
@jessegreenberg I think @terracoda generally captured my feelings

**Comment by terracoda** [comment]
@jessegreenberg, I am closing this issue. We can re-open if the simple checkbox (#317) does not work for users.
