### ISSUE TITLE
Balloon release alert needs to include color

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#225]
Right now, all we hear is "Balloon released..."

From #215

**Comment by terracoda** [comment]
@jessegreenberg, to be clear, the color of the balloon needs to be included in the release alert.
New descriptions for releases are documented in google doc, [BASE: Grid Descriptions Simplified & Revised](https://docs.google.com/document/d/1WNVq5_-Hc9LSdeZVSn2edlwYwpHtGNT1ThFD9NXpZ5Q/edit#heading=h.4z0qsy53v4dw). Simple examples in google doc.

More in context examples are provided in [BASE CWT New Grid Descriptions](https://docs.google.com/spreadsheets/d/1fZq21j65jfJhcsA22pasuBA00kM-cGWxsWDsogwhC64/edit#gid=0) See example 13. Dragging & Releasing for one release example.

**Comment by jobara** [comment]
Just seeing this thread got me thinking that it might be necessary to identify the balloons in a different way, at least visually and maybe to ATs as well. I'm worried that someone who is colourblind may have trouble perceiving the difference in the balloons. This could also be a problem for a low-vision screen reader user, or a someone who is colourblind and paired with someone using a screen reader.

The positive and negative charges are conveniently labeled visual with colours and +/- signs. Perhaps a "1" and "2" could be added to the balloons, or some other identifier.

Sorry for thinking about this late, and if it has already been covered elsewhere.

**Comment by terracoda** [comment]
@jobara, it is nice to revisit this thought in order to summarize what we have done to address it.

We have all actually discussed the color of the balloons a lot already. I have presented different ideas including numbering the balloons. I even thought of putting small differentiated knots or bows on the balloon where the balloons meet the string. The knot/bow idea, I thought would be more useful for people who are colorblind, but conveniently not affect the descriptions at all.

In early interviews, I experimented with referring to the balloons as Balloon 1 and Balloon 2 in the descriptions, but that turned out to just be too confusing for me and the participant. It would be difficult for collaboration between visual and non-visual and/or less visual students. 

In my interviews, I also learned that blind people appreciate color. One participated commented that the color of the balloons made the sim sound more fun. This particular participant commented that they had vision until they were a teenager and that they liked colorful things. This, of course, could vary among participants.

I have not tested the shade and contrast difference between the two colors, but PhET designers do. This can be checked. From my understanding of color-blindness, yellow and green are less often confused than say red and green. Still contrast is important. Here's a useful resource  and comparison on the [different colorblindness](http://www.colourblindawareness.org/colour-blindness/types-of-colour-blindness/). There are many of these examples.

It's important to keep in mind there are several ways to tell the two balloons apart both visually and non-visually in context:

**Visually**
- _Actual color:_ Yellow or Green
- _Level of charge:_ When 2 balloons are in the Play Area they often have each have a different level of charge and in fact it is charge we want the users to explore. For example, what happens when I put  a lot more negative charges one balloon than the other balloon.
- _Focused, grabbed, and not focused states:_ The focus and grabbed states are visually strong, but currently only differentiated by color. I've brought this up before :-)
- _Physical position_, of course: Balloons can be referred to as the one on the sweater, the one at the wall, or the one on the right, the one on the left.

**Differences are similar non-visually**
- _Color in words:_ All descriptions of the balloons refer to either yellow or green balloon. I think this will be good for student collaboration.
- _Level of charge:_ In the non-visual experience there only 3 levels of charge, so this has less differentiation in the non-visual experience, but we feel it meets the pedagogical goals of the sim.
- _Position:_ Upon grab and release, and during dragging the balloon's position is described to the user at different times and in different ways. The position would hopefully be part of user discussion as students discuss attraction or different levels of attraction.

I don't think we need visual number labels, but we may need to look at darkening the green balloon and examining focus and grabbed visual cues before publication. The grabbed state design will be relevant to other sims.

**Comment by terracoda** [comment]
Pedagogically, numbers can be confused as science content, which we do not want.

**Comment by terracoda** [comment]
@jobara and @jessegreenberg, I started an issue https://github.com/phetsims/a11y-research/issues/29. We can discuss related color and design issues there that might be applicable to more sims.

**Comment by jessegreenberg** [comment]
Closing.  With the current design, we have a description like "Released. {{Balloon color}} {{described movement}} + {{other stuff}}
