### ISSUE TITLE
PhET-iO Events stream sends messages when Property.Vector2 sets a value to itself

### ISSUE THREAD

**Issue by samreid** [phetsims/balloons-and-static-electricity#235]
Discovered in https://github.com/phetsims/scenery-phet/issues/262 the PhET-iO events stream keeps showing messages.  When a Vector2 with particular values x1, y1 is set to be the same values x1, y1, the Property thinks it is different and sends notifications.

See also #204

**Comment by samreid** [comment]
In the above commit, I overrode areValuesEqual in 2 spots and this fixed the problem. However, it seems somewhat hack-ish and it may be preferable to have an option or subclass for Property that takes care of this.

**Comment by samreid** [comment]
@pixelzoom I'd love to get your recommendation on this.  I would like to have Property instances that use `equals` instead of `===`.  The current way to do this is by subclassing or overriding the `Property.equalsValue` method.  Should we make it a Property option `useEqualsMethod` or `useReferenceEquality` or create a Property subclass like `ValueProperty` that does that?

I guess I'm leaning toward a Property option (whatever it is called).  What do you think of that?

**Comment by pixelzoom** [comment]
I would proceed with great caution on this.  There are pitfalls to using deep equality. Let's discuss via voice, but the 2 big ones are:
 
(1) If the client isn't also using deep equality, then weird/subtle problems may occur. Example:

```js
1 var homeLocation = new Vector2(100,100);
2 var locationProperty = new Property( new Vector2(100,100) );
3 locationProperty.link( function( location ) {
4   if ( location === homeLocation ) {
5    // do something special when the Node is at it's "home" location
6  }
7 } );
```

The `if` statement on line 4 is unlikely to evaluate to `true`, because the expression should be `( location.equals( homeLocation )`.  And that assumes that `Property` uses this same form of `equals` comparison.

(2) Polymorphism problems. Consider this sequence, where `MyVector2 extends Vector2`:

```js
1 var myVector = new Property( new Vector( 0, 1 ) );
2 var myVector.value = new Vector2(2,3);
3 var myVector.value = new MyVector2(2,3);
4 var myVector.value = new MyVector(3,4);
5 var myVector.value = new Vector2(1, 2);
```

Line 1: How do we determine the type of the Property value? By its current value? By its initial value? What if the initial value is null?  
Line 3: Assignment may (silently) not occur because according to the Vector2 interface, MyVector2(2,3) is equal to Vector(2,3).
Line 4: The current value is now of type MyVector, and the new value is of type Vector2. Will this assignment fail?

That said... If you are going to add this feature, a Property option seems like a reasonable way to do it (better than inheritance). And `useReferenceEquality:true` seems like a fine name and default.

I also noticed... `areValuesEqual` should be `static`, because it requires no access to instance properties.  And presumably once options `useReferenceEquality` is added, `areValuesEqual` should also become `private`.

**Comment by pixelzoom** [comment]
Looking at the examples above, I don't like:

```js
var locationProperty = new Property( ..., {  
  useReferenceEquality: false 
} );
```

It's not communicating the functionality of the Property.  This is clearer:

```js
```js
var locationProperty = new Property( ..., {  
  useDeepEquality: true 
} );
```

**Comment by pixelzoom** [comment]
@samreid said:
>  I would like to have Property instances that use equals instead of ===

This feature has big implications for Property, so I've moved this discussion to https://github.com/phetsims/axon/issues/115.

**Comment by pixelzoom** [comment]
Questions about the PhET-iO problem that spawned this:
> When a Vector2 with particular values x1, y1 is set to be the same values x1, y1, the Property thinks it is different and sends notifications.

How often was this happening, and why was it happening?
Is there another way that this could be solved, perhaps on the client side?
Would it be acceptable to make the analysis code responsible for ignoring these notifications?

**Comment by pixelzoom** [comment]
Unassigning myself. @samreid let me know if/when you want to discuss.

**Comment by samreid** [comment]
@jbphet and I proceeded on https://github.com/phetsims/axon/issues/115 and we could use that solution here.

**Comment by samreid** [comment]
Fixed in the preceding commit, closing.
