### ISSUE TITLE
Balloon movement towards the sweater is handled inconsistently

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balloons-and-static-electricity#240]
Bug found by and report made at the request of @jbphet. 

If the balloon is charged, it will gain velocity towards the sweater. Turns out, the velocity gain is dependent upon the rightmost edge of the balloon and sweater (drawn with red lines). If the balloon's rightmost edge is to the right of the sweater's rightmost edge, the balloon will move towards the sweater:
<img width="1470" alt="screen shot 2017-01-25 at 1 04 46 pm" src="https://cloud.githubusercontent.com/assets/5863899/22307256/83ffe6c0-e2ff-11e6-9d9a-e6c67cdb8adc.png">

The balloon will abruptly stop when both of their edges meet:
<img width="1466" alt="screen shot 2017-01-25 at 1 05 04 pm" src="https://cloud.githubusercontent.com/assets/5863899/22307255/83ff7474-e2ff-11e6-8c7d-b6ca405dcf70.png">

If the rightmost edge of the balloon is ever to the left of the sweater's rightmost edge, the balloon will NOT move. So here the balloon does not move towards the sweater:
<img width="1465" alt="screen shot 2017-01-25 at 1 05 19 pm" src="https://cloud.githubusercontent.com/assets/5863899/22307257/8409e04e-e2ff-11e6-8bfa-253e4e5cfce9.png">

In that above screenshot, if the balloon were the same distance from the sweater, but on the *right* side, the ballon would move towards the sweater. This is already inconsistent behaviour (demonstrated below, somewhat poorly 😞 ).

![base01](https://cloud.githubusercontent.com/assets/5863899/22307790/ad6ee004-e301-11e6-8330-2a89a789fdfb.gif)

@jbphet wishes to make the velocity "check" more consistent along all edges of the sweater and balloon. This will ensure that the balloon always moves towards the sweater if most of the balloon is not overlapping with it (or something like that). Up to @ariel-phet to give the go ahead on this change.

**Comment by ariel-phet** [comment]
I believe I discussed this @jbphet yesterday, and gave the go ahead. Assigning to @jbphet to close or put more detail.

**Comment by terracoda** [comment]
@phet-steele thanks for documenting this bug. I have always wondered why the balloon does not move (i.e., visually attract) when on the left side of the sweater.

Fixing this bug will affect the descriptions that I have designed for this sim. I don't see adding a few more described sticking points on the sweater as a problem, but I will need to create the descriptions once I see how the balloon moves.

In my [described grid](https://docs.google.com/document/d/1WNVq5_-Hc9LSdeZVSn2edlwYwpHtGNT1ThFD9NXpZ5Q/edit) I use the center of the balloon as the point to measure from. I hope that is how it works in the model.

**Comment by terracoda** [comment]
Also, just mentioning @jessegreenberg and @emily-phet in case they have any comments.

**Comment by emily-phet** [comment]
@jbphet It would be helpful to clarify a few reference points in the model. 
- Will the location of the rightmost side of the balloon still be the reference point for determining balloon behavior on release after the bug is fixed? 
- Also, when picking up charges from the sweater, is this done based on the location of the center of the balloon, or some other point on the balloon?

**Comment by terracoda** [comment]
Thanks for clarifying this @emily-phet.

**Comment by jbphet** [comment]
In answer to @emily-phet's questions above:

> Will the location of the rightmost side of the balloon still be the reference point for determining balloon behavior on release after the bug is fixed?
No, it will be the bounds of the balloon.  Any time the bounds of a charged balloon is outside the bounds of the sweater, the force will be applied.
> Also, when picking up charges from the sweater, is this done based on the location of the center of the balloon, or some other point on the balloon?
After the changes I'm making, it will be based on whether the location of the charges are inside an ellipse that should be pretty close to the shape of the balloon and is centered at the balloon's location.

**Comment by jbphet** [comment]
I've implemented a fix on master.  This does change the behavior of the sim a bit, and involved a bunch of code refactoring, so I'm assigning to @phet-steele to verify that the new behavior seems reasonable and doesn't seem to introduce any odd side effects.

@phet-steele - if all looks good, please assign to @terracoda and @emily-phet to make sure that I've addressed their questions.

**Comment by phet-steele** [comment]
@terracoda @emily-phet things look good from here, back to you all.

**Comment by jbphet** [comment]
@terracoda and @emily-phet - I published a dev version to enable you to test this, please see http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.1/balloons-and-static-electricity_en.html.

**Comment by terracoda** [comment]
Btw, I like the saggy strings.

@emily-phet, I do like the more consistent attraction behaviour in the single-balloon scenario. This will be easy to address in the descriptions. Ideally, when I go to change them, I would like to see a center mark on the balloons, and the lines of the visual described grid. This will help me determine exactly where the center point of the balloon's ellipsis during interaction and upon release.

During two-balloon scenarios, the balloons seem much peppier! They really zip around. Is this zippiness intended? I like it. 

Note, I can't actually knock a stuck balloon off the sweater.  I could do this (sometimes) in previous versions. That said, I think it is now actually easier to get other interesting attracting and repelling behavior happening when using the keyboard, or when using the mouse.

While using Safari (10.0.3) with VO (MacOS Sierra 10.12.3) I noticed some strange keyboard focus changes. 
- Two-balloon experiment switch is not focusable, nor operable via the keyboard, and
- I got a pink focus highlight on the sweater, a couple of times. The sweater normally only receives virtual focus, not actual visual keyboard focus because it is not an interactive element.

**Comment by emily-phet** [comment]
@jbphet - I also like the saggy strings, and ability to get good balloon sticking-to-sweater motion from the left side.

Unfortunately, there seems to be some odd behavior introduced in the two balloon scenario. I played with this using Safari. Sometimes the two balloons do not seem to respond to each other (e.g., when both are negatively charged and on the sweater, but I also observed this behavior when the balloons were off the sweater). At other times, they seem to be responding to each other too much...in once scenario I had a charged yellow balloon stuck to the sweater, and a charged green balloon on the right side of the screen (wall removed). When I let go of the green balloon, it moved towards the sweater, then it moved away from the sweater (!) and then swooped down and around the yellow balloon before sticking to the sweater. 

Also, I couldn't get keyboard focus (just using keyboard, no screen reader) to go to the one balloon/two balloon toggle.

**Comment by phet-steele** [comment]
@emily-phet @terracoda see https://github.com/phetsims/balloons-and-static-electricity/issues/241#issuecomment-280093736 for the reasons why we cannot use one balloon to  push another balloon that is on the sweater. In other words, this is intentional and not a result of the recent changes.

**Comment by emily-phet** [comment]
@phet-steele @terracoda @jbphet I'm emailing you all a video that shows some undesired balloon behavior in the two balloon scenario. My guess is that the repulsion between the balloons has somehow been amplified in this version, which probably explains @terracoda impression that the balloon movement is more "peppy" than previously.

**Comment by terracoda** [comment]
It it true they could be too peppy.

**Comment by jbphet** [comment]
In one of the comments above, @emily-phet said,

> Also, I couldn't get keyboard focus (just using keyboard, no screen reader) to go to the one balloon/two balloon toggle.

I've opened a separate issue for this, see https://github.com/phetsims/balloons-and-static-electricity/issues/259.

**Comment by jbphet** [comment]
@emily-phet and @terracoda - I need some clarity on what needs to change.  I've reviewed the video, and the oscillation behavior should be prevented.  I'll take care of that.  I believe that the reason for the balloons appearing more "peppy" than perhaps they did in previous versions is that a bug was fixed where the code was setting the velocity in one place and then clearing it in another, see https://github.com/phetsims/balloons-and-static-electricity/issues/241.  This resulted in a kind of velocity limiting behavior.  @ariel-phet approved the change, but if you're feeling that the current version allows the balloons to move too quickly, I could add a velocity limit.

For right now, I'll work on preventing the oscillation behavior, please let me know if the velocity limit is also desired.

**Comment by terracoda** [comment]
@jbphet, I would like to try out the sim again once the oscillation behaviour does not happen. It's difficult for me to tell what it is supposed to do and what it is not supposed to do. I experimented with real balloons ([Experimental Play: Balloons and Static Electricity](https://www.flickr.com/photos/65291057@N00/albums/72157655633711751/with/18916968694/)) a couple of years ago. In the real world the balloons do not move as fast, for sure. 

I would like to be able to capture the essence of the balloons' movements in words. Too much velocity may complicate this task, but a bit more regularity with also make it easier. For example, more regular balloon movement on the sweater should be helpful for the described environment.

**Comment by emily-phet** [comment]
@jbphet I agree with @terracoda. Can you publish a version for us to play around with?

@terracoda I don't think we can look to real life balloons to decide about speed here...the sim is probably just modeling charge differences. What's most important is that user interaction/exploration isn't negatively impacted by too fast or too slow movement (for visual and non-visual users). I think we're looking for a nice middle ground, where the balloon motion feels responsive, but it's still possible to set up scenarios with a small charge difference where the balloons moves on the slow side...so that there's some anticipation as part of the play. The balloon race is a classic use of this sim, and if it's over in 2 seconds that's not very fun.

**Comment by terracoda** [comment]
@emily-phet, I agree too much speed can be distracting. so we need to find a happy medium that is productive for learners and hopefully, describable :-)

**Comment by jbphet** [comment]
I've reduced the force constant and added an area on the sweater for testing whether the center of the balloon is in the area of the sweater where the charges exist.  This seems to work pretty well - it avoids the oscillation behavior seen in @emily-phet's video, but also allows the balloons to be attracted from the left side or from below.  If both balloons are charged and then placed on the wall, and then the wall is removed, the lower balloon with hit the far wall before it is attracted to the sweater, but it doesn't look that bad to me, and it's due to the basic charge force calculations and would be difficult to change.

Another advantage of this change is that the sim is now using the center of the balloon and the charged area of the sweater to decide whether or not to stick.  This should be very consistent with the "balloon describer", since they are now using the same code for this.

@emily-phet and @terracoda - please try out http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.2/balloons-and-static-electricity_en.html and see if this version does what you need it to do.  If not, I'll probably just go back to freezing the balloons as soon as they cross into the area containing the sweater.

**Comment by emily-phet** [comment]
@jbphet I took a look at this on Safari - it looks great to me!

**Comment by terracoda** [comment]
@jbphet, sorry for the late reply. I think it is working nicely. The movement is slower than from before it was fixed, and I think that's actually a god thing.

The scene switch and the radio buttons are not keyboard accessible in this view. Is that intentional? Or should I start new issues for those items? The radios have never been accessible. they have been turned off for most of my research activities this far. The scene switcher, however, has been keyboard accessible in earlier versions.

**Comment by terracoda** [comment]
@jbphet, is it possible to add a parameter that allows me to use the visual grid, so I can more easily work on the descriptions? @jessegreenberg had one set up for me before. It might be just be "grid", but the following link doesn't swap the background for the visual grid background.

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.2/balloons-and-static-electricity_en.html?grid

Would it possible to do that for me?

**Comment by jbphet** [comment]
@emily-phet said:

> I took a look at this on Safari - it looks great to me!

...and @terracoda said:

> I think it is working nicely. The movement is slower than from before it was fixed, and I think that's actually a good thing.

Based on this input, I think we can close this issue.  @terracoda has some other questions and requests in her comments immediately above that are essentially unrelated to the balloon motion - I'll create separate GitHub issues for those shortly.
