### ISSUE TITLE
motion calculations oscillating when balloon is at a boundary or inside the sweater

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#241]
(note: this has already been fixed, but the issue is being logged for tracking and planning purposes)

The model code that moves the balloons due to applied forces has a bug where each balloon's velocity is continuously set and cleared when the balloon is inside the sweater or at one of the boundaries of its roaming area.  This wasn't causing noticeable problems until the sim was instrumented (see #204), at which point we started seeing a continuous stream of velocity change messages in the aforementioned situations where the balloon appeared to be still.

**Comment by jbphet** [comment]
This was fixed in 9ca73802d5b489963a0ef39e3841aa722b92afb5, 33d6d4798b788807f1fcaeaca919cfa31c63e6d7, and 8dcdf40bb22fe5b741c3924b001d9a641176965e.

**Comment by jbphet** [comment]
The code modifications necessary to resolve this issue have resulted in some changes to the way that the balloons move.  For example, if the user sets up the situation shown in the screen shot below and releases the green balloon, it will now move much more quickly across the top of the screen to the sweater, and will end up higher on the sweater.  This is because previously, the velocity kept getting set to zero on every other time step, so the balloon would move more slowly across the 'ceiling'.

![base-whatever](https://cloud.githubusercontent.com/assets/3082831/22355041/817c8a66-e3e5-11e6-96d2-0adcaf488945.PNG)

**Comment by jbphet** [comment]
Assigning to @ariel-phet to verify that the new behavior is acceptable (or delegate to someone else) and to decide if we should do a new release with this fix.

**Comment by ariel-phet** [comment]
@jbphet showed me this behavior in person and it looked fine (certainly more appropriate than the very slow movement) No need for a new release, since this sim will eventually get republished with keyboard navigation and such.

**Comment by jessegreenberg** [comment]
I believe that commit https://github.com/phetsims/balloons-and-static-electricity/commit/9ca73802d5b489963a0ef39e3841aa722b92afb5 made a change so that one balloon can not be pushed off the sweater when another balloon with charge approaches it, which is possible in the deployed version.  @jbphet was that an intentional change?

**Comment by jessegreenberg** [comment]
The code that was replaced with https://github.com/phetsims/balloons-and-static-electricity/commit/9ca73802d5b489963a0ef39e3841aa722b92afb5 also makes it seem like this should never have been possible, so I am wondering if the behavior in the deployed version is actually an artifact of the bug mentioned in this issue.

@ariel-phet @arouinfar should the user be able to push a charged balloon off of the sweater with another charged balloon?

**Comment by ariel-phet** [comment]
@jessegreenberg that is definitely an interesting question. I actually did not know it was possible to push one balloon off of the sweater with another charged balloon, so thanks for pointing that out.

My take is that it is actually preferable for the balloons to not be able to push each other off the sweater. Here are my reasons:
1.  If you rub a balloon on a sweater, the charge will mainly be on one side of the balloon (the side facing the sweater) so the force between the sweater and balloon, should be larger than the force between two balloons, since I am assuming the charge is stuck to the "underside" of each balloon.
2. It seems to keep more of a focus on the learning goals...sticking to the sweater due to direct attraction, rather than the wall by polarization. I am not sure being able to repel balloons on the sweater is either pedagogically valuable (and I feel like the balloons repelling while stuck to the sweater is not very real world).

@arouinfar?

**Comment by arouinfar** [comment]
@jessegreenberg @ariel-phet the ability to use a balloon to push the other balloon off of the sweater has been present since 1.0.0. It's even used as an example in the sim primer that was recorded about a year ago.

I've found that it's possible to use a very weakly negative balloon to repel a much more negatively charged balloon while on the sweater. This behavior seems wrong to me. 

![untitled](https://cloud.githubusercontent.com/assets/8419308/22991096/72ecd940-f378-11e6-9f2b-2e20b58a334d.gif)

Even if (and it's a big if) a balloon could repel another balloon while on the sweater, I think it would need to be a highly negative balloon being used to repel a weakly negative balloon. In that case, the highly negative balloon would have a large charge density relative to the sweater's charge density, which may allow for the repulsive force to be larger than the attractive force.

However, I think @ariel-phet makes a strong case for completely preventing balloon repulsion while on the sweater. Repulsion between two negatively charged balloons can still be demonstrated elsewhere in the sim.

**Comment by ariel-phet** [comment]
So it seems we are in agreement...the current behavior of not allowing balloons to repel on the sweater is best.

@arouinfar would it be easy to edit out that part of the sim primer?

**Comment by jessegreenberg** [comment]
Thanks @ariel-phet and @arouinfar then I will proceed with #246.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg!

> @arouinfar would it be easy to edit out that part of the sim primer?

@ariel-phet, not particularly. There's only one teaching example in the primer that uses two balloons. The narrator refers to like charges repelling, but makes no explicit mention of the sweater. A balloon is used to repel the other balloon off the sweater three times during this chunk of the primer. What makes things tricky is that the narrator's outro is also recorded over the two balloons repelling, so we can't just edit that part out.

If you want to take a look at the primer, the relevant section is ~1:50-2:10.

**Comment by ariel-phet** [comment]
@arouinfar then we should plan to re-record the primer at some point, not a huge priority, but would be good to do. Please make an issue for that and can probably close this one.

**Comment by arouinfar** [comment]
Done!
