### ISSUE TITLE
Induced charge description: wording change

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#249]
I have never been happy with the induced charge description phrase, so I have a new, simplified version that I would like to run by @ariel-phet, @emily-phet, and @jessegreenberg.

**Current description:** 
At touchpoint, negative charges in wall move away from [[yellow, green]] balloon [[a little bit, a lot, quite alot]]. Positive charges do not move.

I thought first to replace "At touchpoint," with "Near" (see New description 1), but @emily-phet had reservations about that, which was good, because, I thought about it some more. Using nothing with a change in word order, works much better (see New description 2).

- **New description 1:** Near yellow balloon negative charges in wall move away from balloon a little bit. Positive charges do not move. _(If 2 balloons, we need 2 similar sentences)_.
- **New description 2:** Negative charges in wall move away from yellow balloon a little bit. Positive charges do not move.
- **New description 2 (with two balloons):** Negative charges in wall move away from yellow balloon a little bit. Negative charges in wall move away from green balloon a lot. Positive charges do not move.

@ariel-phet, @emily-phet, @jessegreenberg do you agree that **New description 2** is better than both the current description and New description 1?

**Comment by ariel-phet** [comment]
@terracoda I do like the move towards simplicity. Here is my one reservation, but it may not be particularly important. In the visual depiction there is a sense of electrostatic repulsion radially away from the closest point of the balloon. 

Perhaps something like "Negative charges in wall that are in the vicinity of the yellow balloon move away from the yellow balloon a little bit. Positive charges in the wall do not move"

I feel like the "in the vicinity" gives that same idea as what is depicted visually, instead of suggesting all charges in the wall are moving.

Not sure if that can be simplified more or such, but that would be my feedback.

**Comment by terracoda** [comment]
@ariel-phet, how critical is the "radial repulsion" pedagogically? Can a student, potentially get a sense of induced charge without a specific description of the "radial repulsion?" Keep in mind, sonification will convey the subtleties of induced charge much better than any words we can come up with here (in my opinion). 

I originally tried to capture the nature of the "radial repulsion" with "negative charges move away in an arc", and while one participant made a connection between the arc and charge repulsion, it was not something that was easily interpreted. "At touch point", conveys proximity to the balloon, but is somewhat wordy and complicates two balloon descriptions. "Near balloon" has issues that can confuse motion and proximity.

While I like, "in the vicinity", this sim is used with younger learners. "Vicinity" is not a simple word. 

@ariel-phet, I'll ask more explicitly, do you think that "move away from yellow balloon" implicitly captures enough information about proximity to give a student an idea that the negative charges in the wall close to the balloon move away from it? 

My goal here is to shorten the description if at all possible, not make it longer.

**Comment by ariel-phet** [comment]
@terracoda in terms of how critical...that is a bit tough to say. The visual is there for a reason, but it is not strictly a learning goal. As I mentioned, not having this sense was my one reservation/feedback on the description, but I do not think it is critical. I have generally been approaching any a11y questions with the philosophy of "how can this experience best mirror the visual experience" so that is where my feedback is coming from. 

I do not quite think "move away from yellow balloon" implicitly captures enough information about proximity to give a student an idea that the negative charges in the wall close to the balloon move away from it. But again, that may not be important.

**Comment by emily-phet** [comment]
@terracoda @ariel-phet 
I think that the heart of the issue is the difficulty in conveying the visual of induced charge using 1) a short text description, 2) that uses non-technical, kid-friendly terms. We all agree that we're trying to have the visual and non-visual experiences align, but as there are limitations in what can be done graphically, there are limitations on what can be done with text description. @terracoda - please continue with your revision. We'll check interpretations with user testing - focusing on making sure learners aren't getting the entirely wrong impression, which would be that all the charges in the wall move away from the balloon. If that's the impression learners are getting, then we'll have to tweak to something more like "New Description 1" above.

**Comment by terracoda** [comment]
@ariel-phet, and @emily-phet thanks for the feedback and direction:
Decision is we go with the following (New description 2):

> Negative charges in wall move away from [[yellow, green]] balloon [[a little bit, a lot, quite a lot]]. Positive charges do not move.

**Comment by terracoda** [comment]
@emily-phet and @ariel-phet, while updating descriptions for rubbing against the wall, I saw an opening to add location to the induced charge description for the wall. This might address @ariel-phet's concern about the description being too vague.

We could embed the balloon's location against the wall to narrow the idea of where the induced charge effect is actually happening.

- In [[STRING:Location]] wall, no change in charges. (for neutral balloon) 
- Negative charges in [[STRING:Location]] wall move away from [[STRING:Color]] balloon [[STRING:Induced charge amount]]. Positive charges do not move.
- Negative charges in [[STRING:Location]] wall move away from [[STRING:Color]] balloon [[STRING:Induced charge amount]]. Negative charges in [[STRING:Location]] wall move away from [[STRING:Color]] balloon [[STRING:Induced charge amount]]. Positive charges do not move.

**Here are three full examples of the wall's description in the PDOM, should we decide to embed the balloon's location**
- **Neutral balloon:** Wall has many pairs of negative and positive charges. In [[upper]] wall, no change in charges.
- **Balloon with negative net charge:** Wall has many pairs of negative and positive charges. Negative charges in [[upper]] wall move away from [[yellow]] balloon [[a little bit]]. Positive charges do not move.
-  **Two balloons:** Wall has many pairs of negative and positive charges. Negative charges in [[upper]] wall move away from [[yellow]] balloon [[a lot]]. Negative charges in [[lower]] wall move away from [[green]] balloon [[a little bit]]. Positive charges do not move.

**Comment by terracoda** [comment]
And, of course, the description is still a little vague if either or both of the balloons are in the general wall area described as "in wall."

**Comment by emily-phet** [comment]
@terracoda I like it! I think it's a nice compromise. Provides an indication that it's not all negative charges uniformly moving away, but doesn't increase the word count by much. Let's go with this.

**Comment by ariel-phet** [comment]
@terracoda yes, I think this is a nice way to keep the description short but improve the proximity idea.

**Comment by terracoda** [comment]
@emily-phet and @ariel-phet, great!
I like it, too.

**Comment by terracoda** [comment]
OK, new decision for induced charge description in PDOM:

**Induced charge with a neutral balloon:**
-  [+ Wall’s charge description]. In [[STRING:Location]] wall, no change in charges.

**Induced charged with a charged balloon:** 
-  [+ Wall’s charge description]. Negative charges in [[STRING:Location]] wall move away from [[yellow balloon, green balloon]] [[STRING:Induced Charge Amount]]. Positive charges do not move.

**Note: One tricky case...**
If there are 2 neutral balloons against the wall, I think it would be best to revert to the very simple and short general wall description and not refer to location. The balloon’s position will become relevant during interaction, once a balloon is grabbed.
- [+ Wall’s charge description]. In wall, no change in charges.

@ariel-phet, would you agree?

@jessegreenberg and @emily-phet, please chime in when you have time.

**Comment by ariel-phet** [comment]
@terracoda agreed that when the two neutral balloons are in contact with the wall, the simple and short description is sufficient.

**Comment by terracoda** [comment]
No further changes needed now. Final design in https://github.com/phetsims/balloons-and-static-electricity/issues/249#issuecomment-283302776 and in design document.

**Comment by jessegreenberg** [comment]
@terracoda what is the status of this issue?  Can it be closed?  Have these changes been reflected in the design document?

**Comment by terracoda** [comment]
@jessegreenberg, decisions reflected in design document. Closing this issue.
