### ISSUE TITLE
Shouldn't accessibility features be hidden behind a query parameter?

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#277]
@phet-steele found that in [BASE 1.3.1-phetio](https://phet-io.colorado.edu/sims/balloons-and-static-electricity/1.3.1-phetio/wrappers/index) published to the phet-io website, accessibility is enabled without a query parameter. @jessegreenberg and I think it is probably best to hide that under `?accessibility` and Georgia Tech and others can add that parameter in if they want the incomplete accessibility features. 

@ariel-phet @emily-phet please let me know if that doesn't align with your thoughts on the matter.

Otherwise I will continue with a maintenance release and hide it.

**Comment by jessegreenberg** [comment]
Thanks @zepumph! In addition, we discussed that in general accessibility features shouldn't be enabled until publication ready so that this doesn't continue to happen for other sims that are getting deployed out of master for major/minor releases or for phet-io releases.  I will hide accessibility under a query parameter in BASE now.

**Comment by jessegreenberg** [comment]
Hidden in the above commit.

**Comment by zepumph** [comment]
The maintenance release went out. 1.3.3 is live, but there was another release yesterday too for a small bug about the balloon velocity. Here is the latest version. Closing

https://phet-io.colorado.edu/sims/balloons-and-static-electricity/1.3.4-phetio/balloons-and-static-electricity_en-phetio.html?phetioStandalone&phetioValidateTandems=true&accessibility
