### ISSUE TITLE
Reduce threshold for balloon speed to pickup charges

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#283]
@emily-phet and @jessegrenberg were wondering why there is a speed threshold for picking up charges off the sweater.  In order to pick up charges from the sweater, the balloon must move fast enough.

Actually, this is related to a recently closed issue #78.  There is no documentation about why this threshold is there.  Can the threshold be removed or reduced so that it is easier for everyone to pick up charges?

**Comment by arouinfar** [comment]
Actually, I'm not sure why there's a velocity threshold to pick up charges @jessegreenberg . Maybe @ariel-phet has an idea why that's the case.

**Comment by ariel-phet** [comment]
@jessegreenberg @emily-phet @arouinfar I was not around when the model was decided. However, I would think some velocity threshold makes sense. It does require a certain amount of rubbing/friction to get significant charge transfer. So in terms of connection to the real world, one does need to rub a balloon fairly vigorously on a sweater to get the effect we are depicting.

**Comment by emily-phet** [comment]
Is it pedagogically an issue if a student does not have to rub vigorously in order to pick up charges? Right now they don't have to rub vigorously, they just have to move faster than...slow. 

I'd like to propose that we change this to any motion (beyond what may have been an accident up on balloon selection) picks up a charge.

"Any motion picks up a charge" would make the behavior of the visual represntations easier to understand (sometimes it doesn't pick up charges and it's not always clear why), simplify things for keyboard users moving the balloon in discrete steps, and (potentially) those with older devices using a screen reader. It seems reasonable to have some threshold so that just clicking the balloon but essentially holding in place does not result in pickup of charges, but otherwise any motion does.  Note: This change would be consistent with John Travoltage, which does *not* require vigorous foot motion to pick up charges from the rug.

**Comment by ariel-phet** [comment]
@emily-phet seems fine to me.

**Comment by emily-phet** [comment]
@ariel-phet Thanks!

@jessegreenberg Can you make a version of BASE that has an intermediate threshold, and let me take a look? I'm not going to be too picky about this, I think dropping the threshold any amount will be an improvement wrt the charge pickup behavior.

**Comment by jessegreenberg** [comment]
@emily-phet this version cuts the threshold speed for picking up charges in half, could you please take a look?

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.2/balloons-and-static-electricity_en.html?accessibility

**Comment by jessegreenberg** [comment]
@emily-phet reviewed and gave a 👍 closing.
