### ISSUE TITLE
Background color change

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#310]
The background color was recently changed so that it matches the blue background in other sims, but the sweater still has the old blue. The svg asset for the sweater has a transparent background.  @arouinfar would you be able to re-export the original asset with a transparent background?

**Comment by jessegreenberg** [comment]
![capture](https://user-images.githubusercontent.com/6396244/30988683-553517f0-a458-11e7-9ea1-1058c4c5263c.PNG)

**Comment by jessegreenberg** [comment]
Here is a link to  the svg file:
https://github.com/phetsims/balloons-and-static-electricity/blob/master/assets/sweater.svg

**Comment by arouinfar** [comment]
@jessegreenberg I am unable to open the .svg in Illustrator. Do we have an .ai asset for this sweater somewhere?
![image](https://user-images.githubusercontent.com/8419308/31037667-667c4434-a52f-11e7-974e-e818588ec99a.png)

@amanda-phet can you give it a try and see if you run into the same error?

**Comment by jessegreenberg** [comment]
That is all we have in assets. That is strange, I can open it without error in a browser.

**Comment by arouinfar** [comment]
After some troubleshooting, I still can't get sweater.svg to open in Illustrator. Opening my local copy in Chrome resulted in:
![image](https://user-images.githubusercontent.com/8419308/31101108-7c3ee928-a789-11e7-83d1-2bb4dd315f75.png)

Line 15 of the code doesn't appear to have any syntactical differences from other similar lines, so I'm at a loss. 

Spoke with @jessegreenberg, and it turns out the original .svg has a transparent background, but the .png that's used in the sim has the problematic blue background. @jessegreenberg will look into using the .svg directly in the sim, instead.

**Comment by jessegreenberg** [comment]
Looking into the svg, it would not be possible to draw this with Path.  I just  installed Illustrator today,  and for whatever reason it is not having any trouble opening the svg, I will see if I can export it without the backround.

**Comment by jessegreenberg** [comment]
I re-exported with a transparent background,  it looks pretty good:

![capture](https://user-images.githubusercontent.com/6396244/31101874-c8a02e5a-a78c-11e7-8016-0b5c273f1f96.PNG)

**Comment by jessegreenberg** [comment]
@arouinfar how would you like to proceed with the faulty asset?

**Comment by jessegreenberg** [comment]
I re-saved the SVG (chose SVG 1.1, but I don't know what I am  doing), the file looks totally changed, maybe it will be valid now?  If it can be opened by @arouinfar Ill check in the changes.

**Comment by arouinfar** [comment]
@jessegreenberg I can open the updated .svg in Illustrator. Once you check it into GitHub, we should be good to go.

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar, closing.
