### ISSUE TITLE
What is needed to get styled dynamic descriptions into A11y View for BASE?

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#346]
@jessegreenberg, I am wondering what is needed to get the styled dynamic descriptions into BASE's A11y View, similar to the dynamic descriptions in Ohm's Law A11y View.

Could I add the necessary HTML code myself in the A11y content files?

**Comment by jessegreenberg** [comment]
@terracoda I think in https://github.com/phetsims/a11y-research/issues/67 we decided that dynamic strings that need to be styled in the a11y view need to be wrapped with <i> tags with  string formatting in the sim (so the `<i>`'s aren't translatable). We would have to go through and do this for all string patterns in BASE. Is this something you would like me to do, and what is the priority?

**Comment by terracoda** [comment]
@jessegreenberg, I was wondering if it might be easier for me to do it once I am finished the last two description issues. 

It is not high priority, me finishing descriptions is the highest priority.

**Comment by jessegreenberg** [comment]
I think this issue is dependent on progress in https://github.com/phetsims/a11y-research/issues/60, and the only change to the a11y view will be to change the CSS from styling `em`s to styling `i`s. Otherwise changes will need to happen in sim code,  or maybe a combination of scenery and chipper. I remember in an a11y meeting a while ago, @zepumph had a nice idea of how to generalize this, but I  can't find notes from that in related issues.

**Comment by jessegreenberg** [comment]
I added some notes in https://github.com/phetsims/a11y-research/issues/67 about what I think is needed to get styling in the a11y view, it might be good to have a meeting at some point to discuss if the cons in that list are acceptable.

**Comment by terracoda** [comment]
Thanks @jessegreenberg for posting in the phetsims/a11y-research#67 . I'll close this issue as we figure out a more general solution to adding <i> tags.
