### ISSUE TITLE
phet-io branch mismatch

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/balloons-and-static-electricity#429]
It looks like the 1.2-phetio branch's phet-io dependency SHA should be b7e492adf6867c25e3417b41a262b24cd27a5cf8, which does NOT point to the head of the corresponding balloons-and-static-electricity-1.2-phetio branch in phet-io (which is 53b3fc4f32963463a5cbd9789b396c351acd8a9c).

It looks like there were 12 commits on the phet-io branch that were not applied to the 1.2-phetio release branch. Should these be included?

**Comment by zepumph** [comment]
This is very strange. My best guess is that when committing for https://github.com/phetsims/phet-io/issues/1067, I thought I was on master, but instead I was only on that branch. No matter, we now have a BASE 1.3 branch, and no partners use 1.2. So we shouldn't support this. @samreid do you feel differently?

**Comment by jonathanolson** [comment]
We can definitely drop 1.2 off of the "maintenance" list if desired (the manual list and/or the database, depending on when).

**Comment by zepumph** [comment]
I would like to double check with @samreid, then go for it.

**Comment by samreid** [comment]
1.2 was given to two clients, but one of them was given a more recent version and one of them is not using it at the moment.  I don't know how we can tell if the former client upgraded to the more recent version without asking them or maybe checking analytics.  So I can't be certain.  Should we reach out to the client and ask if 1.2 is in use?  Tagging @kathy-phet for a recommendation.

**Comment by zepumph** [comment]
Both clients that we gave 1.2 to have been given 1.3. I would recommend not supporting 1.2. Ideally they should have updated. @mattpen is there a way to look at specific analytics on https://phet-io.colorado.edu/sims/balloons-and-static-electricity/

Ideally on the 1.2.0-phetio version (because that's what our documentation states we delivered to both clients, but perhaps there were undocumented deliveries of maintenance release up to 1.2.2 (from May 2017). I can't be sure. 

If there are no usages, we can drop support.
If there are usages, we should probably make sure that clients aren't using that version anymore. Of course if they are we have to recognize that we have no migration guide to then ask them to update to 1.3-phetio.

If the latter is reality, then perhaps we should delete the 12 commits from the head of the branch and continue on with life. It would be hard for me to trust those commits in a production version.

**Comment by mattpen** [comment]
@zepumph - According to google Analytics, there are 16 pageviews from this summer all from Boulder or Juneau for BASE 1.2 (probably checks related to maintenance deploys?). There were no usages at all for BASE 1.2 from March 2018 - May 2018.  The latest non-boulder usage was December 2017.

**Comment by mattpen** [comment]
@samreid - Is [this comment](https://github.com/phetsims/balloons-and-static-electricity/issues/429#issuecomment-415810504) for phetsims/website#482?

**Comment by samreid** [comment]
Yep, sorry, wrong thread!

**Comment by zepumph** [comment]
What is now needed for us to convince ourselves that it is alright to stop supporting? I foresee that this conflict in our hearts may occur often while we are deciding which sims to drop maintenance support for. 

I think it is alright because until we have a stable version (on the order of 1 year ish hopefully) we can always point a client to the 1.3-phetio branch. @samreid if you agree perhaps we can bring it up at the next status meeting to make sure it's good with @kathy-phet.

**Comment by samreid** [comment]
The analytics suggest we can drop support for the simulation, but for this case (and in future cases like this), we cannot know whether a client with a link to 1.2 is planning to use it in the future (even though they haven't used it recently).  So do we need a way to tell clients about browser bugs that break old simulations, that we are not going to patch?

This will be a harder question to answer in the future, say if we have a hundred thousand hits on balloons and static electricity phet-io, and 5% of them are on a version which we don't want to maintenance release.  We will have to decide where to draw the line, and how to support clients on older versions.

So I think we should close this issue as not needing a maintenance release for balloons 1.2 and create a new issue about dealing with this kind of problem in the future.

@jonathanolson can you drop balloons 1.2 off the maintenance release list?  How do I do this in the future?

**Comment by jonathanolson** [comment]
https://github.com/phetsims/perennial/commit/eae4486139de9dca8e355fed8ca632d76eefc83d removed it from the current manual method. @mattpen can you remove BASE 1.2 from the "active" status from the database? Soon it will be a database-only process.

**Comment by mattpen** [comment]
This was updated in the database. Can this be closed?
