### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#443]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Add and Remove Wall button pointer area much too small

Screenshots:
![Image from iOS](https://user-images.githubusercontent.com/41024075/55907870-23c6da00-5b95-11e9-9f7d-a99bb2439bb9.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe. This looks like a bug to me. @jessegreenberg can you investigate?

**Comment by jessegreenberg** [comment]
This looks familiar I wonder if this was actually fixed elsewhere recently. @KatieWoe was this screenshot taken off of master or the published version on the website?

**Comment by jessegreenberg** [comment]
This was already fixed as part of https://github.com/phetsims/balloons-and-static-electricity/issues/439. Scenery doesn't allow touch/mouse areas that are smaller than the button which is why the button is still clickable. @KatieWoe can you please confirm that this is fixed in master? @arouinfar is there anything else to do for this issue?

**Comment by KatieWoe** [comment]
Does seem fixed on master @jessegreenberg

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg, thanks!
