### ISSUE TITLE
CT does not finish tests

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#454]
CT has not finished tests from at least 10/22/19 to 10/24/19.  These are the tests not being done:
![thesenotdone](https://user-images.githubusercontent.com/41024075/67496879-5a000e80-f63a-11e9-929e-d03cf3d9b5be.png)

**Comment by samreid** [comment]
Bumping priority because this would be useful for https://github.com/phetsims/chipper/issues/860.  The problem I see when running unit tests is:

> Cannot read property 'supportsGestureA11y' of undefined

@jessegreenberg or @zepumph would you have time to take a look?

**Comment by samreid** [comment]
In the above commits, I guarded access to `phet.joist.sim` so it is not accessed during unit tests.  However I don't know if this is the appropriate approach.  @jessegreenberg or @zepumph can you please comment?

**Comment by zepumph** [comment]
I can confirm that tests are running now on CT. 

I have a bit different feeling about how to proceed with this issue. IMO none of these calls should be guarded against, because they should always exist. The `UtteranceQueue` is a dependency to BalloonDescriber. (Feel free to disagree with me 😄 ).  Thus I feel like failling when it isn't there is the correct behavior, and I wouldn't want the graceful code that @samreid added to suppress an actual error.

Instead I rewrote the BASE tests. In the above commits I feel like things got a bit clearer, because it is clear that the tests require those globals to run.

It isn't perfect, because ideally things would be more modular, but I think it is a step in the right direction because it makes the dependencies clear for each test. "BalloonDescriber needs `phet.joist.sim.utteranceQueue`" is loud and proud at the top of `BalloonDescriberTests.js`.

@samreid and @jessegreenberg please review, and let me know if you would rather take things in a different direction. @jessegreenberg please especially review the `beforeEach` callback in BalloonDescriberTests.js. Is it alright recreate and overwrite the local var without disposal for each test? Things are passing but I thought I'd see. If we need to dispose, we can do so in a `afterEach` callback.

The thing I keep coming back to is what used to be in GrabDragInteraction:

`const supportsGestureA11y = () => phet.joist.sim && phet.joist.sim.supportsGestureA11y;`

A lack of `phet.joist.sim` does not mean that we don't support gesture a11y, it means we are in a state that is buggy and unexpected.


Let me know what you think!

**Comment by samreid** [comment]
If we follow this pattern, I foresee a proliferation of functions like this:

```js
const getUtteranceQueue = () => {
  assert && assert( phet.joist && phet.joist.sim && phet.joist.sim.utteranceQueue, 'utteranceQueue needed for BalloonDescriber' );
  assert && assert( phet.joist.sim.utteranceQueue instanceof phet.utteranceQueue.UtteranceQueue, 'UtteranceQueue type expected' );
  return phet.joist.sim.utteranceQueue;
};
```

and this:

```js
QUnit.module( 'BASESummaryNode', {
  before: () => {

    // BASESummaryNode uses many calls to utteranceQueue. This is to support testing
    phet.joist = phet.joist || {};
    phet.joist.sim = phet.joist.sim || {};
    phet.joist.sim.utteranceQueue = new UtteranceQueue( true );
    phet.joist.sim.supportsGestureA11y = false;
  },
  after: () => {
    delete phet.joist.sim.utteranceQueue;
    delete phet.joist.sim.supportsGestureA11y;
  }
} );
```

What if Objects that use UtteranceQueue take it as a a constructor option like so:

```js
new BalloonDescriber(_.hasIn('window.phet.joist.sim.utteranceQueue') ? phet.joist.sim.utteranceQueue : new UtteranceQueue());
```

Would something like that work?

**Comment by samreid** [comment]
Or this could be defined in the `BalloonDescriber` constructor:

```js
this.utteranceQueue = phet.joist.sim.utteranceQueue || new UtteranceQueue();
```

**Comment by zepumph** [comment]
I would be fine with this. I think that @jessegreenberg should take this one over because these are Types that he wrote, and I think he should have a say about how the finished product looks. 

@samreid I agree that a proliferation in those sorts of functions is less than ideal. I feel a bit stuck since utteranceQueue is no longer a singleton. 

One idea! What if in utterance-queue there was an utteranceQueueSingleton getter that could get `phet.joist.sim.utteranceQueue || new UtteranceQueue()` or something like that. Is it gross to put that in utterance-queue? Called `utteranceQueueSingleton`. Then we could change all global usages of utteranceQueue to use that module. Could it live in `joist`? No I don't think so, because it would need to be used in lower level repos like sun/scenery-phet.

**Comment by KatieWoe** [comment]
May be happening again:
![Maybe](https://user-images.githubusercontent.com/41024075/81088537-4de1ed00-8eb8-11ea-9a24-3e29fb46431b.png)

**Comment by jessegreenberg** [comment]
Thanks, it looks like these are generally the assertions failing now, coming from Tandem
Assertion failed: parent should not have child: plusCharges
assert.js:21 Assertion failed: parent should not have child: plusCharges
assert.js:21 Assertion failed: parent should not have child: plusCharges

**Comment by zepumph** [comment]
I wasn't getting the errors reported by @jessegreenberg above, but I was getting  `phet.joist.sim.runOnNextFrame is not a function`, which was from how I was stubbing `phet.joist.sim` to support UtteranceQueue. Because of this, I added one more stub. Tests are now passing on my end. Let's see how CT does.

**Comment by jessegreenberg** [comment]
CT has been clear for some time, thanks!

I like the proposal listed in https://github.com/phetsims/balloons-and-static-electricity/issues/454#issuecomment-599812106 to improve usage of PhET's UtteranceQueue, I moved that question to https://github.com/phetsims/utterance-queue/issues/13.
