### ISSUE TITLE
Should all balloon listeners be added on the same Node?

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#461]
While working on https://github.com/phetsims/gravity-force-lab/issues/189, we noticed that that bug in common code wasn't effecting the BalloonNode. The reason is that the GrabDragInteraction is being added to a sub "image" node, while the `moveableDragHandler` is added directly to the `BalloonNode`. @jessegreenberg can you explain this discrepancy? I'm not sure what the benefit is to have these on separate Nodes, but it seems more confusing.

**Comment by jessegreenberg** [comment]
Coming back to this because I had to review listener code for https://github.com/phetsims/balloons-and-static-electricity/issues/522.  The GrabDragHandler modifies a child of the BalloonNode rather than BalloonNode directly because the BalloonNode itself has content for the PDOM that should contain the PDOM content related to the GrabDragInteraction. It accomplishes HTML that looks like

```html
<div>
  <h3>Yellow Balloon</h3>
  <p>A description of the balloon's location, charges, velocity, etc...</p>
  <div>
    <button>Grab Yellow Balloon</button> // button related to GrabDragInteraction
    <p>Description specific to GrabDRagInteraction
  </div>
</div>
```
