### ISSUE TITLE
Create sound generator for charges moving in the wall

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#486]
The parent issue for this is #479.

In today's sound design meeting we discussed some possibilities for what sound to generate to represent the sounds moving in the wall.  @emily-phet said that it should be thematically similar to the sounds currently generated when the charges jump from the balloon to the sweater.  @Ashton-Morris is going to generate a video or two to give us some ideas and @jbphet will investigate good ways to hook code up to the charge positions that can then be used for controlling the sounds.

**Comment by Ashton-Morris** [comment]
I have created 6 variations of different ideas to bring up and show in the next meeting on Feb 23rd.

**Comment by jbphet** [comment]
We discussed this in the 2/23/2021 sound design meeting, and @Ashton-Morris is going to provide two sets of sound that will be used to cross-fade between to indicate the amount of charge deflection.  The first set will be something like a non-saturated to a saturated sine wave with a comb filter.  The second set should have more of an ambient-ish sound, something akin to what we used for the John Travoltage sim.

I'll assign to @Ashton-Morris for those sounds.  Once that is done, here are some other items that we discussed and I want to make sure to track:
- The sounds for the wall should not be produced until the balloon is at least halfway to the wall from the sweater
- The sounds should stop once the charges stop moving, i.e. sound should not play continuously to indicate charge deflection
- We should try a tremolo effect for when the balloon is moving down the wall
  - volume
  - pitch (i.e. vibrato)
- We should make sure that the sound is perceptible at the smallest amount of deflection but not overwhelming at the largest
- We should be careful not to make the sounds so interesting that they draw people into playing with the wall more than with the sweater

**Comment by jbphet** [comment]
Oh, by the way, there is a prototype sound generator for this sound as of https://github.com/phetsims/balloons-and-static-electricity/commit/2acccf59c5b29295f8b1884276e20f4c736b3611 that we can use for experimentation.

**Comment by Ashton-Morris** [comment]
I have the two sets of sounds we talked about. Fading from the cleaner one and into the saturated one. For the more dynamic second set I used the Hum from John Travoltage for starters. They are .wav since they are meant to loop and I thought they would be easier files to start with.

- charges-wall-saturated-electronic-hum-loop.wav
- charges-wall-electronic-hum-loop.wav
- charges-wall-saturated-sine-wave-loop.wav
- charges-wall-sine-wave-loop.wav

**Comment by jbphet** [comment]
In this week's sound design meeting (on 3/2/2021) we reviewed a version of the charges-in-the-wall sound generator the cross-fades between two different sounds based on the max amount of deflection detected in all of the charges.  The feedback was basically that it felt like too much of a "field", or like the potential energy of the balloon, since it sounded like a single thing changing rather than a group of things.  For the next round of experimentation, we'd like to try creating sounds based on the individual charge positions, but with continuous sounds rather than the discrete, bin-oriented sounds used previously.

@Ashton-Morris will supply some sounds that we can use to cross-fade based on the amount of deflection so that we can try timbre-base changes, and I'll try also altering the pitch.  We'll try this out at the next sound design meeting.

I've captured dev versions of some of the previous prototypes for reference.  They are:
- version with discrete sounds for the charge position, and I think every 3rd charge of the leftmost row is sonified: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.20/phet/balloons-and-static-electricity_en_phet.html
- version with cross-fading based on the max deflection of all charges, and with a threshold about halfway between the sweater and the wall: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.22/phet/balloons-and-static-electricity_en_phet.html

**Comment by Ashton-Morris** [comment]
I have added two different continuous sounds to try.

- charges-synthy-loop.wav
- charges-synthy-loop-one-octave-up.wav
- charges-organ-loop-one-octave-up.wav
- charges-organ-loop.wav

**Comment by jbphet** [comment]
In today's sound design meeting, we worked through several variations for this sound generator.  It still seems like it's hard to tell the difference between the field as a whole and the individual charge motions, which has motivated us to take another look at the discrete bins approach which was tried a while back.  Here are the next action items:

- [ ] Publish a version with a pitch-based change, a single sound hooked to a charge in the vertical center of the wall, and the unsaturated sine wave as the sound source.  This will be used as a comparison point for next steps.
- [ ] Add the ability to do discrete sound generation in bins, similar to what was done for https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.20/phet/balloons-and-static-electricity_en_phet.html, but with the ability to vary parameters like we had for this week.  Also try mapping the bins to specific pitches (scale or chord) and having a threshold so that playing starts earlier

**Comment by Ashton-Morris** [comment]
I have created a few variations for us to test out for the discrete sounds. I think a lot of the work will be us adjusting the parameters of the min-max pitch playback with the discrete sounds in the wall, as well as the starting pitch/playback speed upon first interaction.

- charges-in-wall-blip.mp3
- charges-in-wall-reverse-blip.mp3
- charges-in-wall-blip-001.mp3
- charges-in-wall-blip-002.mp3

**Comment by Ashton-Morris** [comment]
We reviewed the above sounds today and decided to create a few that are similar but more muffled. Having the same characteristics but not drawing so much attention. 

charges-in-wall-blip-002 (to have a longer release and muffled)
charges-in-wall-blip-001 (to be muffled)
charges-in-wall-blip (to have be shorter in length and muffled)

Additionally any similar sounds that fit that criteria I will add if I come across them.

John will be working on a version that has options so the team on their own time and device can experiment with sounds and parameters.

**Comment by jbphet** [comment]
By the way, the setup that we all seemed to like the most at this week's sound design meeting was 3 sound generators, major scale 1 octave up, sound file = charges-in-wall-blip-001.mp3.

**Comment by Ashton-Morris** [comment]
I have added the three modified sounds to our shared sound folder.

- charges-in-wall-blip-001-muffled.mp3
- charges-in-wall-blip-002-muffled.mp3
- charges-in-wall-blip-muffled.mp3

**Comment by jbphet** [comment]
We reviewed the latest in today's sound design meeting and here are some follow-up items:
- [ ] Remove the "non-muffled" sounds from the options
- [ ] Publish a dev version and assign @emily-phet, @Ashton-Morris, and myself to review.  @emily-phet may also bring in @Matthew-Moore240 
- [ ] The code for the other modes that we've been trying out in the sound generator for continuous sounds can be removed - we're most likely going with the discrete sounds

**Comment by jbphet** [comment]
@emily-phet and @Ashton-Morris - I've published a dev version that we can use to experiment with different configurations of the charges-in-the-wall sound generator.  Recall that the control panel for this sound generator is found under the "Options..." menu item in the PhET menu.  Please review for next week, and we can discuss our favorites.  You can take a screenshot of the Options dialog for configurations that you particularly like.

Here's the dev version: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.24/phet/balloons-and-static-electricity_en_phet.html.

**Comment by Ashton-Morris** [comment]
I have two options that I thought fit well.

1. This one was great at capturing the "in the wall" sound. 
![Screen Shot 2021-03-28 at 7 39 05 PM](https://user-images.githubusercontent.com/34492870/112776587-54f87900-8ffd-11eb-9cb2-46d90f2be2fa.png)

2. This was most aesthetically pleasing to me.
![Screen Shot 2021-03-28 at 7 34 50 PM](https://user-images.githubusercontent.com/34492870/112776649-7c4f4600-8ffd-11eb-8dc0-47c4acef5f11.png)

**Comment by emily-phet** [comment]
From our discussion last Tuesday - the "chargesInWallBlip002Muffled" was my favorite, so I started playing around with the options menu from there. 

Here's my favorite: 
<img width="427" alt="Screen Shot 2021-03-29 at 9 50 43 AM" src="https://user-images.githubusercontent.com/5109055/112871690-5add7100-9074-11eb-9459-569288826d9d.png">

In general, I think:
SOUND GENERATORS
- Less than 3 sound generators doesn't give consistent feedback, so we should exclude these scenarios. (For example, holding distance from the wall equal, whether or not a sound is triggered is too variable based on height/location of electron associated with sound generator).
- As number of sound generators increases, I think we run the risk of it starting to sound a bit slot-machine-ish. But, lower sound generator numbers also increase (at least for me) the desire to associate each sound with a very specific thing. When there are more it feels more natural that I shouldn't be trying to figure out exactly what makes a blip happen, but just experience more holistic as the "motion of the charges". 

PITCH MAPPING
- In some cases, the pentatonic scale results in a sound that reminds me of traditional Chinese music, particularly at 0 and higher Octave offset. My preference is always to avoid specific genre associations, so that's why I went with the "Major Scale" pitch mapping. I don't know enough about, or have a good enough ear, to really distinguish much difference across the other options. 

OCTAVE OFFSET
- Seems like @Ashton-Morris prefers slightly higher offset, and I tended to prefer slightly lower offset...but figured there's a reason not to go lower (except for the interestingly useful warping of the balloon release sound, as Ashton indicated above). **@jbphet or @Ashton-Morris can you comment more specifically on your thoughts re higher vs lower sound for charges-in-the-wall?** 

NUM DISCRETE BINS
- Like number of sound generators, need a minimum here, but too many starts to get slot-machine like. Seems like the 5-8 range gets the job done for this sound. 

OUTPUT LEVEL
- I preferred the output level very low, and found it really interesting how in some configurations changing output level behaved as you would expect, and in others it seemed to change the feel of the sound noticeably.

**Comment by jbphet** [comment]
Below are three configurations that I found reasonable.  In general, I found the musical pitch rates, like the major chord and major scale, to be a bit too engaging, and thought they might be distracting, so I tended towards the simple linear pitch mappings.  The one exception was to use a sound without a lot of "tone" to it and shift it down so that it didn't go too high.

I look forward to reviewing these in the next sound design meeting.

![image](https://user-images.githubusercontent.com/3082831/112900329-92faa900-90a0-11eb-8c5d-34c3a06debba.png)

![image](https://user-images.githubusercontent.com/3082831/112900741-187e5900-90a1-11eb-8c4c-22faf95c93f6.png)

![image](https://user-images.githubusercontent.com/3082831/112900848-3c419f00-90a1-11eb-963e-54296b3e8e3f.png)

**Comment by jbphet** [comment]
At the 3/30/2021 sound design meeting we reviewed the settings above and identified two configurations that we thought were reasonably good.  We decided to publish dev versions that use these values as their defaults and get some input from other folks.

@terracoda and @BLFiedler - Please take the two versions linked below for a test drive.  We're looking for feedback on the sound that is being used for the movement of charges in the wall.  Mostly we want to know whether you think they will work in conjunction with description and won't be distracting.  If you have a preference for one over the other, please let us know.  Thanks in advance!

https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.25/phet/balloons-and-static-electricity_en_phet.html

https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.26/phet/balloons-and-static-electricity_en_phet.html

**Comment by terracoda** [comment]
I think I prefer the more musical sound in version 25. I feel this sound is more different than the charge pick-up/transfer sound when rubbing is happening on the sweater.

While testing, I noticed 
1. no edge sounds, so I created an issue for that.
2. a long rub sound if I jump the balloon to the wall with J+W. I will create an issue for that now.
3. that I get the wall sounds even when charges are not shown in wall, I'll create an issue for that too.

**Comment by BLFiedler** [comment]
I like 25 over 26 as well.

Unrelated to the sound itself, when moving fast I think it's pretty easy to miss the nuance the pitch change even with maximum charge buildup. I noticed there is some room where you begin to repulse the wall electrons without any sound.  I'm not really sure what sound option would change this, but have you tried starting the blips "sooner" with less initial displacement/force? May require more "bins" or a broader pitch range.

**Comment by jbphet** [comment]
Based on the feedback above, I've set the default configuration to the more "musical" sounds reflected in dev.25.  I also tweaked the size of the first bin based on @BLFiedler's observation about when the first sound is triggered.

I'll also try hooking up the new peak detector to see what the max output is and see if I should adjust the level of the individual sound generators so as not to be too loud.

**Comment by jbphet** [comment]
I've adjusted the algorithm that sets the output level for the individual sound generators such that the peak output values from this node when it's master gain node is set to 1 is right around 1.0.  This should make its output level pretty similar to that of a sound clip, so the output level settings should be similar.  Note that I optimized this change for the current default configuration, and if this changes, I may need to do another round of it.

**Comment by jbphet** [comment]
@emily-phet has requested that we leave the dialog for manipulating the charges-in-the-wall sim in place until right before we publish.  This will potentially support some work being done by @BLFiedler.

I'm going to unassign myself for the moment, since there isn't any immediate work to be done until we get more feedback or decide to make changes.  It should stay open though, and I'm marking it as blocking publication because there is a lot of code in this for enabling configurability via the options dialog.  All of this should be removed before publication.

**Comment by jbphet** [comment]
Hey @BLFiedler - @emily-phet had asked me to keep the options-for-charges-in-the-wall-sounds dialog around for a while.  This was mostly in support of some of the work the you were doing, or had planned to do.  Do you still need it?  I'm trying to figure out if I can and should remove it as part of moving this along towards publication.

**Comment by BLFiedler** [comment]
Yes! I was actually planning to use it this Friday with the hillside students, so I would very much like to have to instantiated still. If it's easier to create a dev version or something similar so we can continue to use it without fear of messing up publication, I would be happy with that.

**Comment by BLFiedler** [comment]
Alright - this specific work is done and it sounds like there is work for a more general feature like this in the future, which is exciting. Done and can be cleaned up @jbphet

**Comment by BLFiedler** [comment]
Quick summation of quick BASE interviews with attention to the Charge Repulsion sound:
- Two students, 8th (less conceptually comfortable, named electrons unprompted) and 9th grade (more conceptually comfortable, brought up repulsion, attraction, electrons, protons, and more unprompted)
- Both identified the charge repulsion sound during exploration and **matched it to the action that was occurring in the wall** (although this did not overlap with realization that the negative charges in the balloon were repelling, which came (slightly for 9th) later in both interviews). 
- Neither found the charge repulsion sound annoying. 9th grader found it pleasant. 8th grader only predicted the balloon attraction sound would become annoying after lengthy exploration.
- Neither identified the charge repulsion sound as inappropriate (though the 8th grader was uncertain it was appropriate either since that does not make a real life sound). 
- 9th grader (who has interviewed with us before a few months ago on self-voicing sims) commented unprompted that all of the sounds in this sim were very pleasant and complemented each other well for a whole experience. Self identifies as a picky sound person who is easily overwhelmed by a busy soundscape (paraphrasing).

Based on these interviews, the charge repulsion sound does not appear to be a hinderance. @emily-phet @jbphet

**Comment by jbphet** [comment]
Cool, thanks @BLFiedler.  In today's sound design meeting we turned the volume of this sound generator down a little bit, so I think we're good to go on this.  Closing.

**Comment by jbphet** [comment]
During today's sound design meeting a "heads up" was given that there may ultimately need to be some modification to this sound generator so that it works well with the description.  I'm going to reopen, but leave this unassigned, and then will make sure it gets checked before the next publication.

**Comment by emily-phet** [comment]
@jbphet I spoke with @terracoda today about the current lack of alignment between when the induced charge at the wall responses are heard, and when the charges moving in the wall sound is heard. 

@terracoda's recommendation was that @jbphet and @jessegreenberg meet to share with each other how the each (description of the induced charge, and charge-in-wall sound) are triggered. If straightforward to, try to address the lack of current alignment by adjusting when the *description* indicates the induced charge effect to align with the current onset of the charge-in-the-wall sound. If that is problematic, then the alternative it seems would be to adjust the sound to match the description, but since the sound has already been designed and evaluated with the current alignment to the visuals, starting by shifting the region in the description when the induced charge is described seemed like the best place to start.  

My hope is that this change is straightforward, and this serves as a quick knowledge sharing opportunity across description/sound, and that in the future we're keeping an eye out during implementation about the potential needs of associating description and sounds to (ideally) the same parameter/regions so we don't have to do so much manual fine-tuning like this. 

Please let me or @terracoda know if you have any questions or concerns.

**Comment by jessegreenberg** [comment]
@jbphet @jessegreenberg and @emily-phet met to discuss what would ideally be aligned. For this issue by "alignment" we mean the trigger in the model that would initiate the description of induced charge in the wall. This is not to say that the description for induced charge should play at the same time as the sound (which is how I first interpreted the issue). We briefly described how description and sound each determine this and agreed it seemed reasonable and more correct to get them to use the same model properties. @jbphet and @jessegreenberg will meet next week to work on this together.

**Comment by jessegreenberg** [comment]
@jbphet and I met to work on this today. The sound and description code now use what is currently `BalloonModel.inducingChargeProperty` to determine when to describe/play sound that there is an induced charge in the wall so that sound will never happen without a description about induced charge and vice versa. In addition, there is some clean up and refactoring that I can do to make the alignment a bit more clear. @jbphet  and I identified the following:

- Pull the `inducingChargeProperty` into the parent model, it shouldn't be on the individual balloon.
- Rename the `inducingChargeProperty` to `inducedChargeLargeEnoughProperty` or something like that, to indicate more clearly that there could always be an induced charge, but it has to be large enough to display.
- Possibly use displacement rather than force to trigger description/sound of induced charge.

**Comment by jbphet** [comment]
@emily-phet, @Ashton-Morris, and I reviewed and discussed the relationship between sound generation and description quite a bit during today's weekly sound design review meeting.  At the moment, @jessegreenberg and I have hooked up a sort of "master power switch" for sound generation and description so that they are enabled and disabled at the same time (as @jessegreenberg describes in the previous comment), but this works out to be a pretty loose form of coordination.  When I demonstrated this at the meeting, the initial response was that it didn't seem like much coordination at all.

During the course of the discussion, we eventually decided that the ideal behavior was that sound generation and description would occur together in pretty much all circumstances, whether the user was interacting via the mouse or the keyboard.  This would be a pretty big change to the current code, so I proposed something that I _think_ will be pretty close to what we're looking for in most circumstances that should be easier to implement.  The proposal is that the sound generator has knowledge of when the changes in wall charge positions occur due to a non-mouse based drag event (e.g. a keyboard drag) and always generates a sound in such cases.  Since the description appears to also always say something about the charges in these cases, this should appear reasonably well coordinated, i.e. the code will be producing sound and description on each keyboard-event-triggered change.  During the discussion we termed this approach "the shortcut".  The longer road would be to centralize the logic that decides whether to generate a sound or a description and use that as the an trigger for both the sound generator and the description generator.

If, in the course of @jessegreenberg and my investigation, it turns out to be easier to do the longer road than the shortcut, we'll do it.  Or at least try it.

The next step then is to try the shortcut and see how it pans out.

**Comment by jbphet** [comment]
I moved the charge sound generator into BASEView so that it could make use of drag information from the balloons, and then added that ability to the charge should generator.  We just reviewed it in the sound design meeting, and the decision is that it's "good to go".  The code will need a bit of cleanup, after which this issue can be closed.

**Comment by jbphet** [comment]
@Ashton-Morris - A couple of things:
- [ ] I'll need a .wav version of the final sound, which prior to the rename I just did was called `charges-in-wall-blip-002-muffled`
- [ ] I renamed that file to `charge-deflection`, so you'll need to update it in your records

**Comment by Ashton-Morris** [comment]
- [charge-deflection.wav](https://drive.google.com/file/d/1axCZyOy4teX0T9aM5ez4I4jC1qAe6Vwc/view?usp=sharing)

**Comment by jbphet** [comment]
Asset added, so this is now done.  Closing.
