### ISSUE TITLE
Redeploy from master with new features

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#495]
We're getting close to redeploying this sim with a set of new features that improve its usability.  I will be in the lead on this, and I want to make sure that I and the rest of the team are clear on what will and will not be in this release.  Here's the list of new features:

- sound
- pan & zoom
- preferences menu

Some things that were discussed but that are not going into this release are:

- mobile a11y
- improvements to how the descriptions work (prevention of stack-up)
- phet-io improvements (the phet-io version will not be published at all)

**Comment by jbphet** [comment]
I'm going to unassign this until we're getting close to being ready to redeploy this sim, and at that point I'll self-assign and organize internal and dev testing of these features.

**Comment by arouinfar** [comment]
@kathy-phet and @zepumph mentioned that we could potentially roll PhET-iO into the upcoming redeploy. I reviewed the current state in Studio, and I don't think that this would be a low-effort publication. I would not include the phet-io-brand in this upcoming release @jbphet.

My full notes are in the [PhET-iO design doc](https://docs.google.com/document/d/1DzI3MdJbvPIydd447zBoZit_uj3RuDmj3yfJkGHEazc/edit#heading=h.kgt54lql80wx), but here are some things that would need to be addressed before PhET-iO publication:

 * Lots of over-instrumentation 
 * `view.controlPanel` needs a lot of reorganization 
 * There are a few cases where the data type may not be appropriate (e.g. using a string instead of an enum) 
 * The charges in the model might need to be upgraded to a PhetioGroup

**Comment by jbphet** [comment]
The question of whether to release the phet-io brand in this upcoming release was discussed in the 5/20/2021 phet-io meeting and the developer meeting.  In the former, it was decided to _not_ release the phet-io brand.  In other words, the upcoming release will be phet brand only.

In the developer meeting we discussed the process for doing this in order to make sure that the tools will handle it.  After some discussion, we decided that the best approach is to remove "phet-io" from the list of supported brands in the `package.json` file in the release branch as soon as that branch is created.  This will prevent any accidental releases of the phet-io version from the release branch.

**Comment by jbphet** [comment]
In today's a11y planning meeting we discussed the upcoming republication of this sim.  In the [opening comment above](https://github.com/phetsims/balloons-and-static-electricity/issues/495#issue-850769025), we had decided that mobile a11y and fixes for pile-ups of descriptions would not be addressed in this release.  However, there may have been enough advances in the common code and sim-specific cleanup that these features actually work reasonably well.  In the meeting, we decided to publish a dev version, have @terracoda review it, and let us know whether these features are now in decent enough shape that we could consider stating that they are supported in the sim.  And, if not, they may be far enough along that we could list these features as being in the "prototype" state on the website.

@terracoda - Please review [this dev version](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.32/phet/balloons-and-static-electricity_en_phet.html) with respect to mobile a11y and description, and log your thoughts on whether we should list those features as supported, being prototyped, or not supported.  After that, please assign the issue back to me and I'll take it from there.

**Comment by terracoda** [comment]
- 3 finger swipe up, started reading from top - all initial state descriptions are perfect
- got mobile instructions for grab button - good
- when dragging there are no pile-ups, but some directional responses are spoken instead of more relevant charge or landmark position info
- getting visual grab hints on mobile
- got a couple of incorrect position descriptions when playing with 2 balloons (these position)

So, it's not perfect for mobile release, but it is very good and can be a a prototype release on the A11y sims page.

**Comment by terracoda** [comment]
@terracoda to check A11y sims page and update link.

**Comment by terracoda** [comment]
I'll make a new issue for checking link on website, and @jbphet you can take this issue over.

**Comment by jbphet** [comment]
The 1.5.0 version was just published, so this is now done.  Closing.
