### ISSUE TITLE
User suggestion: show polarization caused by positively charged object (allow sweater to be moved)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balloons-and-static-electricity#498]
> I would love some way to show that polarization will also be caused by a positively charged object. Maybe the sweater can be moved close to the wall?

**Comment by arouinfar** [comment]
This is an interesting suggestion, but it would require significant design and development changes.

* The positively charged sweater would not stick to the wall like the balloon does. The gravitational force on the sweater is much larger than the electrostatic force between the sweater and the wall. The model of this sim does not include gravity, and adding it is not an option. We could get around this with some handwaving saying we are looking top-down and the sweater is lying on the ground, but we'd likely need to make other visual changes to the sim to pull it off -- the blue background doesn't look like a floor and the balloon strings would also be strange. It also muddies the interpretation of a balloon sticking to the wall -- does it stick because of electrostatic attraction or because it is simply sitting on the floor? 
* If there is a positively charged sweater in the play area, there must also be at least one negatively charged balloon also present. The balloon will almost always more attracted to the sweater than the wall (unless the balloon is much closer to the wall than the sweater). If the sweater is near the wall, the balloon will be on the sweater, meaning the sweater+balloon group is effectively positive so there wouldn't be any visible polarization effects on the wall. To satisfy the user's goal, we'd need to be able to hide the balloon altogether.
* Any changes to the sim would require changes to the sound design, alternative input, and descriptions. 

While seeing polarization caused by a positive object could be powerful, the context of this simulation is inappropriate for this learning goal. If we were to shoehorn this goal into the simulation, it would require significant changes and come at a high cost. This is not a user request we can accommodate.
