### ISSUE TITLE
User suggestion: add insulator-wall and conductor-wall for the balloon to interact with 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/balloons-and-static-electricity#499]
a user suggests to dd insulator-wall and conductor-wall for the charged-balloon to interact with, in that case, the students can see the difference between interactions between charged objects and insulators and conductors. 

Also, he suggested being more clear about what the actual wall in the sim is, an insulator, conductor, or dielectric (probably in the teacher tips). The teacher thinks that the actual behavior of the sim does not really represent any of them and that their students get confused when he asks them to classify the objects in the sim.

**Comment by DianaTavares** [comment]
The user [sends this link](https://javalab.org/en/conductor_and_insulator_en/) as an example of how the sim can show the interaction between a charged object and a conductor on an insulator wall: 
![image](https://user-images.githubusercontent.com/26031501/116724110-de58ed80-a9a5-11eb-93ee-660459b4ff0c.png)

![image](https://user-images.githubusercontent.com/26031501/116724060-cbdeb400-a9a5-11eb-92f6-5aff0f8d530a.png)

![image](https://user-images.githubusercontent.com/26031501/116724171-f2045400-a9a5-11eb-82e6-564c056738ea.png)

**Comment by arouinfar** [comment]
Thanks for passing this along @DianaTavares. The wall is a dielectric and therefore polarized by the presence of an electric field. Since the sim models a real-world situation, I think it would be inaccurate and confusing to introduce a non-dielectric insulating wall or a conducting wall. I'd advise against making this change in the sim, but I updated the teacher tips to clarify that the wall is a dielectric.
