### ISSUE TITLE
Sound design review

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#501]
Much of the sound design has been implemented and the mix is nearly finalized.  It's time to have a review and make sure the various designers and other stakeholders are good with what has been implemented.

**Comment by jbphet** [comment]
Here's the first version to review: Version to review: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.28/phet/balloons-and-static-electricity_en_phet.html

Reviewers: Please check yourself off of the list below once you've reviewed, and add any objections or suggestions below.  We want to get it published fairly soon, so please log only thoughts that you feel strongly about.

- [ ] @arouinfar 
- [ ] @Ashton-Morris 
- [ ] @terracoda

**Comment by emily-phet** [comment]
I like it a lot - the sound balance is great! 

One minor thing (no change necessary, just wanting to note it for completeness):
There were a few times when moving the charged balloon from the sweater towards the wall when I felt the last "charges in wall" sound was a little unexpected (since the charges move very little), but I don't think this is a major issue. It probably just a minor preference thing of the exact setting for the first bin.

**Comment by Ashton-Morris** [comment]
The sound design is amazing! ^__^

**Comment by terracoda** [comment]
I think the sonification and sounds sound wonderful as well.

I have a similar concern to @emily-phet 's comment. The description of the induced charge effect actually happens even earlier than the sonification. Of course, when exactly the description starts depends on how much negative charge is on the balloon. I tried a couple of amounts and in both cases I would hear the description before the sound started.

I ideally they (the sound for and the description of the induced charge effect) should start at the same time, and I think the sound starting and finishing points are better than the current starting and finishing spots of the description of the induced charge effect.

I also noticed that the Interactive Description is really piling up. This concerns me.

I'll open a separate issue for the pile-ups as I am not sure how the publication of sonification will affect the interactive description.

**Comment by terracoda** [comment]
There is already an issue for the pile-ups in #491

**Comment by arouinfar** [comment]
Overall, I really like the sounds and I think it all comes together nicely.

At first, I struggled a bit with interpreting the sound related to the charges in the wall and it took me a while to figure what was going on. The first time I encountered the sound, it was completely unexpected. I thought it was possibly related to the balloon's position (balloon was at midpoint between sweater and wall). The movement of the wall charges was pretty subtle when the sound was first triggered, so perhaps that led to my initial confusion. 

That said, the sound led me to focus a bit more on bringing the balloon near the wall, which could be a useful nudge for students. I'm not sure if there have been student interviews yet, but it might be something to keep an eye out for.

**Comment by terracoda** [comment]
I am commenting that @jessegreenberg and I made some progress on the description pile-ups in #491. There are still a couple of issues to resolve, mainly #506 and then the timing of the description of charge movement and the sound of charge movement can be synchronized.
 
#508 is not sound related, and I think I verified that #507 is not an issue. It might soon close.

**Comment by BLFiedler** [comment]
May have been linked to the wrong issue when I wrote this. Summarize thoughts in #486 , but will repaste here:

Quick summation of quick BASE interviews (5/20/21, 5/24/21) with attention to the Charge Repulsion sound:
- Two students, 8th (less conceptually comfortable, named electrons unprompted) and 9th grade (more conceptually comfortable, brought up repulsion, attraction, electrons, protons, and more unprompted)
- Both identified the charge repulsion sound during exploration and **matched it to the action that was occurring in the wall** (although this did not overlap with realization that the negative charges in the balloon were repelling, which came (slightly for 9th) later in both interviews). 
- Neither found the charge repulsion sound annoying. 9th grader found it pleasant. 8th grader only predicted the balloon attraction sound would become annoying after lengthy exploration.
- Neither identified the charge repulsion sound as inappropriate (though the 8th grader was uncertain it was appropriate either since that does not make a real life sound). 
- 9th grader (who has interviewed with us before a few months ago on self-voicing sims) commented unprompted that all of the sounds in this sim were very pleasant and complemented each other well for a whole experience. Self identifies as a picky sound person who is easily overwhelmed by a busy soundscape (paraphrasing).

Based on these interviews, the charge repulsion sound does not appear to be a hinderance.

**Comment by terracoda** [comment]
I am just going to add, that Balloons and Static Electricity will not be published with iOS mobile accessibility because of some remaining issues for that platform #508 and possibly others. BASE is available as a prototype version with iOS VoiceOver accessibility.

**Comment by jbphet** [comment]
@kathy-phet hasn't had a chance to review this, so we're going to say it's approved as is.  Closing.
