### ISSUE TITLE
Consider making balloon pointer area smaller

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balloons-and-static-electricity#548]
**Test device**
iMac 

**Operating System**
10.15.7

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/721

When the balloon is against the wall by the reset button, it appears to the user that reset button is mostly unobstructed by the balloon and can easily be pressed. In actuality, only a tiny portion of the reset button can be selected. (This is a different issue than what I reported in https://github.com/phetsims/balloons-and-static-electricity/issues/522)

**Steps to reproduce**
1. Move balloon to bottom corner of sim next to wall.
2. Try to press the reset button

**Visuals**
![Screen Shot 2021-10-21 at 11 37 51 AM](https://user-images.githubusercontent.com/87318828/138312323-5e4ebe6b-9085-44ee-8b26-f37c35e25db5.png)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balloons and Static Electricity‬
URL: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.2/phet/balloons-and-static-electricity_all_phet.html
Version: 1.5.0-rc.2 2021-10-11 21:55:48 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Language: en-US
Window: 1288x875
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
The pointer areas have been like this for a long time, but I agree that some improvement is possible.  I believe the original intent was to make it so that the balloon could be dragged by the little nub at the bottom of the balloon if the user wanted to, which is why the ellipse is as large as it is.  Our ability to create more complex shapes has improved since this sim was originally written, so I'll look into making pointer areas that better match the shape of the balloons.  If this turns out to be difficult, I'll bail, since we've managed to live with it like this for as long as we have and I can't afford to speed too much time on it.

**Comment by Nancy-Salpepi** [comment]
This is much improved! Thanks!
