### ISSUE TITLE
Selected balloon should move to the foreground

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balloons-and-static-electricity#82]
I checked the original java sim, and the selected balloon moves to the foreground. This behavior is not present in the html version.

**Comment by terracoda** [comment]
@jessegreenberg, I second this question. Is it intentional that the grabbed Green balloon does not move to the foreground?

**Comment by jessegreenberg** [comment]
Good question @terracoda, I don't know if this was a decision during the port or perhaps the sim was ported before Scenery supported moving things to the foreground?

@arouinfar @ariel-phet do you have any thoughts on this issue?

**Comment by arouinfar** [comment]
@jessegreenberg I think moving the selected balloon to the foreground makes a lot of sense. I wasn't a part of the design decisions made for the port, but I would be a little surprised if this was an intentional change.

**Comment by ariel-phet** [comment]
@jessegreenberg not an intentional change to the best of my knowledge. Again this was one of the first sims to be converted, so there is some vestigial weirdness. Feel free to make this change as it seems like a superior and more consistent UX

**Comment by terracoda** [comment]
@jessegreenberg, when the grabbed balloon moves to the foreground, I think it is fine that it does affect the order of the balloons in the Parallel DOM. However, that said, this is an interesting accessible design question. I would want to watch this in interviews to see if a static order makes sense to both non-visual and visual keyboard users.

FYI, if it is easier programmatically to make the order in the PDOM dynamic, let's discuss the pros and cons of a dynamic order further.

**Comment by jessegreenberg** [comment]
Static vs. dynamic order in the DOM doesn't make much of a difference in terms of difficulty to implement.

But I do prefer to keep the order the same in this case. I think it could be confusing if the user tabbed to the yellow balloon then tabbed to the green balloon to pick it up and then had to tab to the yellow balloon again because the green balloon was moved in front of the yellow one.

**Comment by terracoda** [comment]
@jessegreenberg, I agree for the same reasons that the balloon order should remain static in the PDOM.

**Comment by jessegreenberg** [comment]
In the above commit I fixed a scenery problem where adding and removing nodes from the display caused blur event listeners to fire because the browser triggered the blur event if the dom element had focus while it was being removed from the document. In BASE, this meant that moving a balloon to the forground was causing it to lose focus.

**Comment by jessegreenberg** [comment]
This was done in the above commit.  @terracoda  as a general practice, should focus also move the balloon to the foreground?

**Comment by jessegreenberg** [comment]
Right now, the balloon just moves to the foreground when it is picked up.

**Comment by terracoda** [comment]
Good question @jessegreenberg. I think I need to mull this over a little and play with the latest version. I need to think about the cases where the balloons are already over lapping. 

How does this work in the mouse interaction?

**Comment by jessegreenberg** [comment]
> How does this work in the mouse interaction?

The balloon moves to the foreground when clicked with the mouse.

**Comment by terracoda** [comment]
@jessegreenberg, sorry, I forgot about this issue. 

I think moving balloon to the foreground **as it is grabbed** makes the most sense. Nothing changes until the user makes an intentional grab interaction.

On release the balloon still has focus and it should stay in the foreground until the other balloon is grabbed.

**Comment by terracoda** [comment]
@jessegreenberg the sim is working right now as described above, so can we close this issue?

**Comment by jessegreenberg** [comment]
I believe so @terracoda thanks!
